### ISSUE TITLE
counties.csv loads when viewing rankings

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1001]
Just noticed the `counties.csv` is loading when you view the rankings page.  We don't need that there do we?

**Comment by pjsier** [comment]
Hmm, I thought we had fixed this in #647, but we shouldn't need it

**Comment by pjsier** [comment]
Ah actually looking at it again, that stopped the duplicate, but the `SearchService` is calling `counties.csv` when it's initialized. We should probably move the code from its constructor into a separate function that's only called when the map tool loads
