### ISSUE TITLE
Rankings should use general tweet if state data is unavailable

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#1008]
Alaska's tweet currently comes out similar to "-1.0% of renter homes were evicted in Alaska in 2016. Badger had the highest rate." We should use the general area type tweet if the state data is unavailable

**Comment by pjsier** [comment]
Realizing now that the problem with this option is that `getDefaultTweet` pulls the average from the current list data, so we would need to update that or do some refactoring. Would it make more sense to just have a fallback tweet that maybe just has "Eviction Lab City Rankings. Find out how your city compares at {{link}}"? This would only be for states that have null data

**Comment by Lane** [comment]
Yeah, that works for me
