### ISSUE TITLE
Incorrect Safari user agent detection

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1019]
User agent for Chrome (on Windows at least) has the word `safari` in it, so it is incorrectly getting flagged as safari in `app.component`.

Need to adjust the user agent detection in `platform.service`'s  `isSafari` function to be more specific.

**Comment by pjsier** [comment]
It looks like we just need to check that it has Safari and does not have Chrome in it based off of this https://www.denisbouquet.com/javascript-targeting-safari-only/

**Comment by Lane** [comment]
Sounds good... so weird that Chrome has Safari in there.
