### ISSUE TITLE
Rankings div overlaps footer after fast scroll on iOS 11, iPhone 7

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#1030]
<img width="438" alt="screen shot 2018-04-04 at 9 32 16 am" src="https://user-images.githubusercontent.com/8291663/38314155-39dc3f20-37eb-11e8-9436-38f6e4695d2e.png">

**Comment by pjsier** [comment]
Reproduced on iOS Chrome as well. Looks like this has to do with the URL bar displaying and viewport units

**Comment by Lane** [comment]
I just did a quick check on this using iOS simulator and was able to reproduce.  Dropping the background / box shadow when the panel is not visible seems to work.  Want me to put in a PR for that or do you have something on the go?

**Comment by pjsier** [comment]
Go for it! I haven't really started looking into it
