### ISSUE TITLE
"Please remove a location to add another"

### ISSUE THREAD

**Issue by jmcarp** [EvictionLab/eviction-maps#1076]
Not sure what this warning means or how to avoid it:

<img width="449" alt="screen shot 2018-04-07 at 10 53 51 pm" src="https://user-images.githubusercontent.com/1633460/38462535-cb0046ea-3ab6-11e8-8c81-ddd24d01eb52.png">

To reproduce:
* Go to https://evictionlab.org/map/#/2016?geography=block-groups&bounds=-77.527,37.467,-77.456,37.498&type=er&locations=5106728,-77.443,37.447%2B5124496,-77.375,37.581%2B51760,-77.493,37.525
* Click any location on the map

**Comment by Lane** [comment]
Hi Joshua, we currently have the maximum number of locations you can compare at once set to three.  If you want to look at some more areas, you'll have to remove one of the locations by clicking the "X" button that's highlighted in the image below:

![image](https://user-images.githubusercontent.com/21034/38462616-597b4182-3aa7-11e8-8862-a905e58ce677.png)

**Comment by jmcarp** [comment]
Thanks! I think the interface isn't very clear on this point--since I didn't have the "view full comparison" tab open, I couldn't see how to remove locations. I also didn't explicitly add any locations, so it was surprising to see an error about having too many. It might be helpful to expand the error message to explain what the user is being told to do, or to auto-open the comparison tab so that the user can actually see where they can remove locations.

**Comment by Lane** [comment]
Definitely!  Thanks for the feedback, it's much appreciated.  We're discussing how we can handle this better and will keep this issue open as we work towards a solution.
