### ISSUE TITLE
Add "Census Tract" or "Block Group" to locations in cards

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#1078]
I've seen some mentions that the census tract or block group names, since they're all numbers, can look like an additional statistic, and might not be clear to people who add them through searching an address. Since the labels can only get to a certain link, it could be worth adding "Census Tract" or "Block Group" before or after the ID

<img width="201" alt="screen shot 2018-04-09 at 10 53 26 am" src="https://user-images.githubusercontent.com/8291663/38508293-6ef13f92-3be4-11e8-8f89-e0b7dfd93f04.png">

**Comment by Lane** [comment]
Yeah, looks like there is space to fit that in so I'm good with it!

**Comment by Lane** [comment]
@pjsier do you know what "block group" or "census tract" would be in Spanish?

**Comment by pjsier** [comment]
We have them in the translation for layers now (Secciones Censales and Grupos de Cuadras), but they're plural so it's slightly different

**Comment by pjsier** [comment]
Closed by #1091
