### ISSUE TITLE
Embed Enhancements

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1089]
Seeing the [embed in use](https://www.curbed.com/2018/4/9/17216054/eviction-records-data-matthew-desmond-princeton) brought up a few things for me that I thought might be nice to have.

  - a button to "customize this map", which would open the map with the current parameters on the Eviction Lab site, where the user could adjust eviction / census variables.
  - adding labels to the legend that says which variables are represented on the map.  I think with an embed people are less likely to know it is interactive.  Looking at it as if it were an image, you can tell the range of values represented on the map, but you can't tell what those values are (e.g. Eviction Rate, % African American) without interaction.

Opening this issue to ask:
  - Are these worthwhile additions?
  - If so, what might they look like on the embed?

**Comment by Lane** [comment]
Linking the logo to the map view makes sense to me.

**Comment by pjsier** [comment]
The second one is harder, but I'm starting to think adding the legend labels outside of the tooltips would be really worth it given a few places have used the embed already. Could it be similar to the export (screenshot below)?

<img width="410" alt="screen shot 2018-04-12 at 9 14 23 am" src="https://user-images.githubusercontent.com/8291663/38682957-f2130686-3e31-11e8-9ee5-d8d777490737.png">
