### ISSUE TITLE
Error when no features present

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1098]
- **Device/Browser**: MBP/Chrome
  - **Resolution:** 1280x703
  - **Problem**: Error thrown when trying to reduce queried features in `getUnionFeature` when there are no features currently rendered.
  - **Expected**: The function handles when there are no features rendered and doesn't throw an error.
  - **To Reproduce:** Tough to reproduce, but I've managed a few times.  If you quickly zoom in to the map, then select "Block groups" before the tiles have rendered, you'll get this error.

![image](https://user-images.githubusercontent.com/21034/38629894-885f7bb2-3d72-11e8-8687-881b50bdaf50.png)

**Comment by pjsier** [comment]
Not sure if this is the same or just similar, but this gets thrown frequently for the embed as well. That could be related to the fact that it never sets the highlight features, but might still be calling `updateHighlightFeatures` with the expectation that some are present if locations are selected in the URL
