### ISSUE TITLE
Drop styles using vh for mobile / tablet

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1103]
`vh` cannot be used in a predictable way thanks to the shrinking location bar. On initial load when the full location bar is present, the time slider is pushed slightly off the screen because `100vh` is taller than the actual viewport height.

![image](https://user-images.githubusercontent.com/21034/38647665-b7b8d8bc-3daa-11e8-96a0-59afe6591df3.png)

 Height of the `map.component` should be set via javascript in `ngAfterViewInit` instead.  All child styles using `vh` should use % relative to the parent instead

**Comment by pjsier** [comment]
Hadn't noticed this initially, but #1105 reintroduces the jumpy mobile scroll. Could we re-add the observable that only re-updates the height when the width of the viewport changes so that it doesn't happen?

**Comment by Lane** [comment]
Good catch, should be fixed in #1106

**Comment by pjsier** [comment]
Closed by #1105
