### ISSUE TITLE
Low count flags on lower geographies

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1130]
Need to implement flagging for low count areas at higher zoom levels than states.

From James H.
> Just talked to Matt, we are going to hold off on implementing these for now as we actually think we should take a more nuanced approach to the flagging. We’ll try to get that together for you in the next week, and once Lillian and I touch base we can set up a phone call to go over the flags.

Keeping this issue open until a method is determined.

**Comment by pjsier** [comment]
Closed by. #1183
