### ISSUE TITLE
Generated link in tweet is not correct

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1170]
From Katie:

> I’m having a bit of a problem with the tweet function on the map, as it looks like it’s dropping cards: https://evictionlab.org/map/#/2016?geography=cities&bounds=-90.395,36.95,-77.132,43.527&choropleth=pr&locations=3918000,-82.991,39.983%2B4260000,-75.118,40.002
I selected Philly, Indianapolis and Columbus and it keeps dropping Indianapolis. Not sure what’s going on but wanted to flag it!

From James: 

> I selected Philadelphia County and tried to tweet, and this is what came up: Philadelphia County had 10,264 evictions in 2016. That's 3.48% of renter homes, or 28.04 per day. Find eviction rates for your area at https://evictionlab.org/map/#/2016?geography=states
Note the incomplete / wrong URL there.

**Comment by Lane** [comment]
Able to replicate, looks like the link generated does not include the last selected location.

**Comment by pjsier** [comment]
Closed by #1171
