### ISSUE TITLE
Memphis, TN fails to trigger card popup via search box

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-maps#1176]
Not sure if this is a more widespread issue, but when searching for Memphis, TN, I get the result you see below. Can duplicate across browsers, but other cities (including those I tested in TN) work fine.

Note that the map travels to Memphis; just doesn't trigger card. I can then click in the map and the card appears.

<img width="1060" alt="screen shot 2018-05-07 at 2 03 32 pm" src="https://user-images.githubusercontent.com/33635008/39717028-0b21de2c-5200-11e8-94f7-173e586bb747.png">

**Comment by pjsier** [comment]
It looks like it's finding the shape layer for Memphis, but it's not finding the `GEOID` for Memphis in the label/bubble layer. Not entirely sure why yet

**Comment by pjsier** [comment]
If we change the query zoom for the `cities` layer from 8 to 7 it picks up Memphis. I'm guessing it's just on the border of the tile for the shape layer, so the center is a little bit outside. The difference in data loaded between zoom 7 and 8 isn't that significant either, so updating that will fix it without any real side effects
