### ISSUE TITLE
Facebook Share

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#118]
Link the facebook icon in the footer row to a facebook share dialog.

- [x] Add open graph metadata to page (title, description, localization)
- [x] Use dynamic image if possible, or fallback to static image

[Open Graph Tags](https://developers.facebook.com/docs/sharing/best-practices#tags)
[Example FB code](http://www.fbrell.com/saved/2779dc018c325d85d650a3b723239650)

**Comment by pjsier** [comment]
Should we consider this closed by #133 and make a separate issue for social media metadata?

**Comment by pjsier** [comment]
Closed by #133
