### ISSUE TITLE
Twitter Share

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#119]
Add click binding on Twitter icon in the footer row to open a pre-populated "compose tweet" dialog that includes the link to the current view.

Dialog can be open with a link like:
https://twitter.com/intent/tweet?text=Hello%20world

**Comment by pjsier** [comment]
Is this also closed by #133? Also, is it an issue that people won't be able to access any of the sharing items unless they've selected a feature on the map? If that's intentional it's fine with me, just realized it though

**Comment by pjsier** [comment]
Closed by #133
