### ISSUE TITLE
Conform chart section to Lane's revised UI

### ISSUE THREAD

**Issue by amygroshek** [EvictionLab/eviction-maps#1209]
![Chart_UI_revision](https://user-images.githubusercontent.com/746182/69206377-19e55c00-0b12-11ea-9832-82c3aec31653.png)

**Comment by amygroshek** [comment]
@James Minton @lane As I’m working on this, gotta say, I think the line and bar graph selector as-is is kind of cute. I’m reluctant to change it to a dropdown. I like that so many of these controls allow for immediate interaction, don’t require a lot of clicks/touches. By going from toggles to selects and more complex dropdowns we maybe implicitly favor mouse over touch… Changing the eviction data type selector to a dropdown makes sense, that would save a lot of horiz space in the layout. The date selection will do the same but for line graphs only. For bar graphs, by switching from a simple select to a complex dropdown with a date picker, no space is saved and perhaps some is lost. Same for the line/bar graph switcher. No space saved there. I wonder what the overall goal is with these changes?  For most of these controls we’re increasing the interaction complexity for not a lot of saved space. Is there some other reason? It occurs to me that maybe we are trying to make them match the map controls? (edited) 

agree that by switching to the dropdowns we lose the ability to immediately switch some of the options.  it’d be good to check and see how many user’s are interacting with these controls.  if people are switching between bar / line a lot, might make sense to keep it as a toggle.  i suspect people change start / end dates a lot less often, i don’t really understand why someone would.  the goal of switching to the condensed form is to:
- only show the current selections (instead of all options) to help the user scan and understand what the chart is showing.  it has no title, and having all options spread out make it tough to easily scan
- group all of the controls in one area to prevent overwhelm and give the user a single area to manipulate the graph options
- provide interface elements for selection that are consistent (currently using 3 different types of interface elements for selection) 

agree that by switching to the dropdowns we lose the ability to immediately switch some of the options.  it’d be good to check and see how many user’s are interacting with these controls.  if people are switching between bar / line a lot, might make sense to keep it as a toggle.  i suspect people change start / end dates a lot less often, i don’t really understand why someone would.  the goal of switching to the condensed form is to:
- only show the current selections (instead of all options) to help the user scan and understand what the chart is showing.  it has no title, and having all options spread out make it tough to easily scan
- group all of the controls in one area to prevent overwhelm and give the user a single area to manipulate the graph options
- provide interface elements for selection that are consistent (currently using 3 different types of interface elements for selection) (edited) 
2 replies

James Minton  10 hours ago
 it’d be good to check and see how many user’s are interacting with these controls.
I don't think we have GA tags for these controls, FYI
Screen Shot 2019-11-19 at 12.09.19 PM.png 
Screen Shot 2019-11-19 at 12.09.19 PM.png



lane  10 hours ago
dang

we also don’t have labels on the controls (e.g. “chart data” or “chart type”), which could be confusing in a mobile view.
image.png 
image.png


Amy Groshek 12:04 PM
Ah, ok. That’s helpful. Thanks @lane.
lane 12:09 PM
no problem, not sure there was much discussion around this so thanks for the feedback. happy to keep the UI the same for the graph if we don’t have team consensus or if it doesn’t fit within time / budget constraints
James Minton 1:26 PM
When this was first proposed, I was sold on it pretty quickly and willing to let it eat into the budget a bit, because of its improved consistency (within the tool itself and with the map controls), and the addition of labeling.
But I also didn’t consider the tradeoff of adding interaction steps, and I appreciate having that pointed out. And generally appreciate any critical feedback on anything we’re considering for production.
My feeling now is that while the extra steps are something of a drawback, it’s not so big a deal because I agree that the ability to rapidly toggle probably isn’t that useful, nor is time range selection particularly.
Honestly bar graph and time range both seem a bit superfluous to me, but maybe get some niche usage. (But in any case I’d rather not remove features as part of an “update”—hate when apps do that, unless the features really suck.) (edited)

**Comment by Lane** [comment]
implementation details are pretty vague on this, having only the screenshot.  let me know if i can help out by creating a more detailed spec or wireframe, or if you'd like a hand with any of the implementation.
