### ISSUE TITLE
Range Select component

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#1221]
# Specification
Need a range select for start / end years.

- should accept input containing label for the component
- should accept input array of values
- should accept input of selected start value
- should accept input of selected end value
- should have output emitter that emits start / end values once they have been applied
- should display a label along with the start and end value using the select box pattern (e.g. 2000 to 2016)
- on select box press:
  - open the range selector that displays all available values in grid format
  - should have "apply" button
  - should have "cancel" button
  - should highlight any values including and between the selected start and end values
- on value press:
  - highlight pressed value
  - on second value press (if it comes after first value)
    - highlight all values between start and end
- on "apply" button press
  - emit the start / end values
  - close the range selector

**Comment by james-minton** [comment]
Noting this only allows forward / in-sequence selections -- e.g. if you select 2016, you cannot select a prior year and must cancel out. Wondering if we can alter this to allow year selections in any direction.

**Comment by Lane** [comment]
yeah that would be better, will update
