### ISSUE TITLE
Address all dependency/security issues across all EL repos

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-maps#1231]

**Comment by Lane** [comment]
i'm going to upgrade our version of angular so i will update any vulnerable dependencies on this repo.

> across all EL repos

i'm good with this, but in future cases we should aim to open issues on the relevant repos.  keeps things a bit more organized and we don't end up cross referencing issues from different dependencies

**Comment by Lane** [comment]
A note, the following packages are deprecated and will need to be re-implemented using alternatives:

- `ng2-page-scroll` (*replaced with `ngx-page-scroll`, should be fixed*)
- `ngx-carousel` (*should replace with [ngu-carousel](https://github.com/sheikalthaf/ngu-carousel)*)
