### ISSUE TITLE
Notification for users with older browsers

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#136]
Need to create and style a component for users with browsers that don't support WebGL with a link to information on downloading newer browsers

**Comment by pjsier** [comment]
The older version of IE 11 that isn't supported isn't throwing the error. I think we can just use the `mapboxgl.supported()` function if that works? More info here https://www.mapbox.com/mapbox-gl-js/example/check-for-support

From trying it out in the IE console in BrowserStack it looks like it checks the difference between them. I can open a PR for this now

**Comment by Lane** [comment]
Yep, that's good with me.  Didn't realize mapbox had a built in function.
