### ISSUE TITLE
Improve placeholder text for search

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#145]
In user testing, it was not clear to everyone that the predictive search was for map locations. Improve the placeholder text to make this clearer

**Comment by Lane** [comment]
Checking in on this... is "Search for places" the revised placeholder text for search?  If so, can we close this?

**Comment by pjsier** [comment]
I'm also wondering about this, not sure if that is the revised text

**Comment by pjsier** [comment]
Just confirmed that it's the correct text, closing
