### ISSUE TITLE
Add labels for years in cards

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#148]

**Comment by pjsier** [comment]
This will probably require some design input, mainly because we're already right at the edge of how much we can fit in the cards. It can't go in the top segment because we're using all the height there already, and even if we try a `float: right` there the parent location labels are long

<img width="425" alt="screen shot 2017-12-26 at 1 55 00 pm" src="https://user-images.githubusercontent.com/8291663/34362795-9113ac28-ea44-11e7-8288-4e4906ef6140.png">

**Comment by Lane** [comment]
Year will not be added to cards.
