### ISSUE TITLE
Location cards outline state

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#150]
Look into highlighting the borders of any selected feature in location cards. 

**Note:** not sure how to handle this for location cards selected from different layers. The hover highlight is a separate layer, so we could potentially just leave the outlines there even if the current layer doesn't match. Also, look into making the highlight colors match the card colors

**Comment by Lane** [comment]
Wonder if we could also add a marker?  Then the outline disappears when they switch layers, but the marker could remain.

**Comment by pjsier** [comment]
It could work, but I wonder if that would get confusing with the bubble layers on top of it? Also, realizing that this will probably be dependent on #152

**Comment by pjsier** [comment]
Thinking through this now, this could be more trouble than it's worth because of the issues in #152. Even if we add a bounding box to the URL, setting the outline would require getting the actual shape which we can't store in the route params

**Comment by pjsier** [comment]
The only way I can think to do this easily is to create an S3 bucket that has one GeoJSON file for each feature, organized by layer and GEOID (because FIPS alone will be duplicated with zip codes and tracts). Then we'd pull the GeoJSON for the shape if it's not available. It might be worth considering how much this feature is worth it, but if it's a priority I think we can make it work

**Comment by Lane** [comment]
Could we add additional "highlight" layers to the map, then filter based on name / parent location in the active features?

**Comment by pjsier** [comment]
The problem is if the object isn't in the visible layer/features we would have no way of getting its shape. If we wanted to only show selected objects that are in the current map layer that could work though

**Comment by pjsier** [comment]
I think it could make sense to just have another function that waits for onZoomEnd and adds any features that are currently visible? And maybe we just don’t worry about features in different layers that haven’t been toggled yet
