### ISSUE TITLE
Scroll shakes in data panel on iOS Firefox

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#163]
When scrolling down (not up) in the data panel on Firefox on an iPhone, the screen shakes and I have to release it before it’ll move. We probably won’t have a lot of users on this, but from the bugs we’ve seen so far usually if something popped up on Firefox it could cause issues on other browsers. Safari on iOS is fine here though

**Comment by pjsier** [comment]
Strangely enough, this has something to do with the routing. I'm looking more into it now, but after going through the commit history it only becomes an issue once routing is introduced. I commented out the functionality of `updateRoute()`, and changing that alone fixes it, so I'll look more into what part of routing is causing the scrolling to shake

**Comment by Lane** [comment]
Ah, that makes sense... Could it be jumping to the top every time the route changes?  I could see using a hash route causing that to happen.  Need to look into preventing hash jump if we stick with hash routing.

**Comment by pjsier** [comment]
Didn't think of that, but definitely a possibility! Also, one other think I realized is that it only happens when the top search bar in the browser is displayed. If you manage to scroll past it so that the header and footer disappear in the browser window, the issue goes away.

I've dug into it enough at this point that it may just be worth writing off as a browser bug, especially if it has to do with the implementation of the search bar disappearing

**Comment by pjsier** [comment]
I just found another bug on Firefox for iOS where the map doesn't resize if you select a card and then unselect it, leaving a white gap under it. At this point I think it's safer to not support Firefox iOS, because these are definitely browser implementation bugs that we may not be able to fix

**Comment by Lane** [comment]
The white gap issue was a CSS issue that should be fixed with #230.  I think we could probably support Firefox iOS, but agree on skipping things that are due to browser implementation bugs.

**Comment by pjsier** [comment]
Ah gotcha, yep that PR fixed the white gap, but the scroll shaking seems to be related to their implementation of showing and hiding the search bar

**Comment by pjsier** [comment]
It may have been removing parallax, but this is fixed to the extent that it isn't just a browser implementation issue. Just tried it out on Firefox iOS. One thing I did notice is that it needs to be exempted from the `software-button` class, so putting in a PR for that now that it looks like it'll work otherwise

**Comment by pjsier** [comment]
Closing this as fixed/sort of a duplicate of #455
