### ISSUE TITLE
Fix layer auto-switching

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#169]
Previously auto-switching of layers was turned off once a layer was selected and only turned back on after zooming out past the minimum zoom of a layer. Now it seems to stay on regardless

**Comment by Lane** [comment]
I think this is fixed, @pjsier can you confirm?

**Comment by pjsier** [comment]
Yep! I left it open just in case, but after that auto switching PR you just did it should be fine. Closing
