### ISSUE TITLE
Update progress indicator to match mockups

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#172]
Progress indicator should be at top of app screen overall. I was also thinking of adding an issue to use the progress indicator after someone's selected a search feature but before the data for it is loaded. Should we have it have a fixed position at the top level component and then listen for loading events from child components?

Mockup:
![image](https://user-images.githubusercontent.com/8291663/32851706-5dd74e28-c9fb-11e7-8765-44255b52b375.png)

**Comment by Lane** [comment]
Yep, fully agree with using it for any loading tasks on the page instead of being map-specific

**Comment by pjsier** [comment]
Closed by #173
