### ISSUE TITLE
Select display label on mobile

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#179]
Right now on mobile the select component only shows the currently selected value. Either we should display the dropdown category label on mobile in general, or we should at least display the category label if the selected label is "None" so we don't get this (screenshot below). Displaying the category label is probably the better solution so that it isn't too tacked on

<img width="628" alt="screen shot 2017-11-16 at 9 33 47 am" src="https://user-images.githubusercontent.com/8291663/32899779-7bae9e90-cab1-11e7-8f91-1eed72e8dd57.png">

**Comment by Lane** [comment]
closed by #180
