### ISSUE TITLE
UI Select: Turn off page scrolling when menu is open

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#188]
Page scrolling should be disabled when a UI select menu is open so that the page doesn't scroll down when the user is trying to get to the bottom of a select menu.

**Comment by pjsier** [comment]
@lane it looks like this is still an issue on mobile (at least for me on iOS Chrome). Should we reopen this or make a new issue?

**Comment by Lane** [comment]
Ah, good catch.  I only have it listening to mousewheel right now, so will also need to add touchmove for touch scrolling.  We can just reopen this.
