### ISSUE TITLE
Zooming quickly on the map in Firefox moves into the data panel

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#189]
Using Firefox for MacOS, if you're zooming on the map with a card selected and you swipe down quickly on a track pad to zoom out, it can scroll down to the data panel without selecting "View More Data". Couldn't replicate this on Chrome or Safari.

Relating to this and #163, I'm wondering if there's another option besides `ngx-page-scroll` to use for the scrolling functionality. Their [README](https://github.com/Nolanus/ngx-page-scroll) makes it look like they don't test against Firefox, and if we want to support Firefox it could be worth finding another package

![scroll](https://user-images.githubusercontent.com/8291663/33214490-2e30047a-d0fa-11e7-913d-f86e5d89381d.gif)

**Comment by Lane** [comment]
Good catch!  It looks like this might have to do with the wheel / scroll event being sent to the page instead of the map absorbing all of those events.

I'm cool with switching from `ngx-page-scroll`, but it is only used to handle manually scrolling between the map and the data panel.  I don't think it has any impact on regular scrolling of the page.

**Comment by pjsier** [comment]
From playing around with this more, I think it's most likely just relating to lag. Firefox responds more slowly, so if the map doesn't respond to the scroll event quickly enough the browser seems to default to a normal scroll. I'm good with considering this a won't fix if that's the case

**Comment by pjsier** [comment]
This actually may have to do with using the custom `debounce` function for listening to `wheel` events. I thought the zoom performance issues were mostly related to firing events on all zooms, not just `zoomend`, but looking into the performance stats there's a big toll from calling `setTimeout` multiple times while zooming. I'm gonna try and modify it to see if that improves things

<img width="493" alt="screen shot 2018-01-10 at 7 19 10 am" src="https://user-images.githubusercontent.com/8291663/34774889-c86584ec-f5d6-11e7-9f67-c888a8576336.png">

**Comment by pjsier** [comment]
It seems like we've narrowed this down to a general performance issue that we've been addressing, so I'm closing this in favor of other performance-related issues since we may never fully close it

**Comment by Lane** [comment]
Had this happen to me a couple times today on the staging URL, so I'm going to reopen.  No for sure way to reproduce yet, but seems to happen when I'm zooming from a high zoom level to a low one.

**Comment by pjsier** [comment]
This may be fixed in the next Mapbox update. I saw that they have some issues about performance degradation in zoom in 0.43, so I rolled back to 0.42.2 locally and it's significantly better. It was also a lot harder (but not impossible) to reproduce this bug. It looks like the fix for that will be in the next release

**Comment by pjsier** [comment]
After the update to `mapbox-gl` 0.44.0, I don't think this is entirely fixable. It looks like it's being caused by what's mentioned above: a really fast zoom can overwhelm the map and cause it to no longer absorb all zoom events, so they're then forwarded to the document.

It doesn't seem like we want to prohibit all scrolling if the map is open, but that seems to be the only way to fully fix it. I'm good with closing this again, since it'll still happen, but the best way to mitigate it seems to be general performance improvements

**Comment by Lane** [comment]
I'll have to try `0.44.0`, but I was experiencing this even without really fast zooms so I'd like to dig into this a bit still.

**Comment by Lane** [comment]
Just tested a bit with `0.44.0` a bit and can't seem to make this happen anymore... now that I think about it I think it might have been #491 causing it.  I'd say it's probably good to close too.

**Comment by Lane** [comment]
Crap, okay I can reproduce.  If I zoom all the way out on the map and keep scrolling a bunch via trackpad with the cursor over the map, it will eventually jump down.

Not a critical bug as it probably won't happen to standard users, but should probably fix before launch.  Could potentially be fixed by throttling wheel events.

**Comment by pjsier** [comment]
@Lane in that case, #479 might help with it? I think my latest updates are working better, even if they still make some compromises

**Comment by Lane** [comment]
Will check it out, but it looks like wheel events that are throttled in #479 are only the ones that make it to `document`.  I think we'd need to throttle the wheel events that are absorbed by the map to fix this.

Other potential fix is to turn off page scrolling on map zoom start then turn it back on when map zoom ends... but it might not be the best solution depending on how long the delay is before zoom end fires.

**Comment by pjsier** [comment]
Ahh good point, yeah that wouldn't necessarily fix it. I think the `zoomstart`/`zoomend` approach could work, and since those only fire once per zoom event it shouldn't be a performance hit

**Comment by pjsier** [comment]
This seems to be fully resolved by #546, closing
