### ISSUE TITLE
Support prototypes with non-hash URL?

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#194]
Looking in the Angular routing docs for a different issue, they have [a code snippet](https://angular.io/guide/router#set-the-base-href) that supports using HTML5 routing on a dynamic base href. Could be worth looking into, and potentially triggering with an environment variable for prototype builds

**Comment by Lane** [comment]
Sorry, missed this until now.  Is there any benefit of using non-hash routing over the hash routing?

**Comment by pjsier** [comment]
Not sure, but I remembered that it's the way we originally started out, so I figured I'd bring it up. If you don't think it's a priority we can close it

**Comment by Lane** [comment]
I'm fine with either way! Without the hash definitely looks nicer, and could potentially fix the mobile firefox jumping issue if it's caused by hash updates.  I think if we have time it's worth trying out.

**Comment by pjsier** [comment]
I looked a little into this, and the big problem seems to be loading the assets with the `base` tag. Right now we're setting it with `href="./"`, which works because we're using the hash route. When I switched it to non-hash routing, it fails if there are any URL params present.

Since we're planning on the production deployment being at `evictionlab.org/rankings` and `evictionlab.org/map`, we'll probably need the base route to stay relative so we'd keep running into this issue. I'm sure there's a way of doing it, but I'm more skeptical that it's worthwhile now

**Comment by pjsier** [comment]
Was thinking through this a bit, and I think we can do this in a pretty straightforward way, partially relating to #644. If we set S3's error template to index.html as well as the index template, then it'll forward all routes that fail to index.html without needing the hash route.

For Cloudfront we can have two origins for the tool (like we'd been talking about already), one that responds to `/map` and one that responds to `/rankings`, as well as S3 buckets for each of them. We can deploy the main site to the `/map` bucket and set its base href to `/map` with associated map metadata. Then, we can modify the metadata in the index.html file for rankings, but leave the base href the same, and deploy that file alone to the rankings bucket. It should load the assets from the map bucket so that we don't need to duplicate those, but we can still have the separate metadata.

Not going to work on this until we start putting the production deployment together, but hopefully it's a way of knocking out both issues

**Comment by pjsier** [comment]
Closing this for general URLs with #753. Removed prototypes from Travis since we aren't really using it and it was pretty slow anyway
