### ISSUE TITLE
Include other census variables in dropdown

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#202]
The data for multiple census variables is ready, so we can go ahead and add it to the dropdown

**Comment by pjsier** [comment]
Another one that I'm not sure it needs to be done, but is worth considering because we may get asked why other variables aren't displayed

**Comment by Lane** [comment]
Yeah, I think we should probably get this one in.

**Comment by pjsier** [comment]
Closed by #253
