### ISSUE TITLE
Add real social media metadata

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#203]
Currently using metadata based on the preview site, but we'll need to update that and potentially make some of it dynamic

**Comment by pjsier** [comment]
Not sure if this needs to be done by next week, but it should be relatively straightforward to put in something that looks a little more realistic so we can show the functionality

**Comment by pjsier** [comment]
I don't think we actually have the copy for this, so added the feedback label

**Comment by Lane** [comment]
Checking in to see where we're at with this, do you know if we received some copy to use?

**Comment by pjsier** [comment]
I haven't checked the content doc recently, but I don't think so?

**Comment by Lane** [comment]
K thanks, I'll check in and see where we're at.

**Comment by pjsier** [comment]
Moved this to the Production Implementation milestone since it's just swapping out some text now
