### ISSUE TITLE
Route Error on Load

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#210]
Minor error that doesn't seem to impact functionality.  Reproduction steps:

- Open the map tool in chrome
- Look at the console, an error along the lines of this will show:

```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '-123.049,22.135,-71.13,51.312'. Current value: '-123.049,22.135,-71.13,51.312'.
```

Issue is with mapView being modified before it should be.

**Comment by pjsier** [comment]
Closed by #232
