### ISSUE TITLE
Handle areas in line graph with no data

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#212]
For the map data, we had to use -1 as a placeholder because it doesn't seem like there's a good way of representing null in the vector tiles. We'll have to convert that before sending it to the graph, otherwise it shows up like this

![screen shot 2017-11-30 at 2 14 45 pm](https://user-images.githubusercontent.com/8291663/33452789-fd0c4dde-d5d8-11e7-97cd-c0c1dcd19e65.png)

**Comment by Lane** [comment]
From the PR:

> Looks great! I'm wondering if we should split the line on areas with no data (maybe something like this https://bl.ocks.org/mbostock/3035090), but that would probably be a separate UI issue

Agreed, I think some kind of split or dotted line would be good.  The filter is an okay quick fix, and I'll leave this issue open for the additional enhancement when time permits.

**Comment by pjsier** [comment]
Looks like this is still an issue for the bar chart too, but I'm guessing we'd want to come up with some way of signifying no data there so it doesn't look like zero?

<img width="841" alt="screen shot 2017-12-02 at 11 21 39 am" src="https://user-images.githubusercontent.com/8291663/33517970-ff494306-d752-11e7-98e7-aa2f5b659539.png">

**Comment by pjsier** [comment]
Changed the issue title to reflect the current state better. We're treating -1 as null, but we want to potentially use a dotted line or other way of handling broken data. We also need to make sure that the axis spans the full width of the time range selected. Currently, if the year range selected is 2010-2016, and the data is null from 2010-2012, the X axis will start at 2013

<img width="1151" alt="screen shot 2017-12-06 at 9 48 50 am" src="https://user-images.githubusercontent.com/8291663/33667822-84ccbc3e-da63-11e7-80ca-23aeda003c3a.png">

**Comment by pjsier** [comment]
If we're thinking of doing a dotted line for the parts with no data, this seems like a good way to go https://github.com/pbeshai/d3-line-chunked

We'll definitely need to change a large chunk of the implementation in the d3-graph package, so let me know what you think of that
