### ISSUE TITLE
Increase road visibility at higher zooms

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#227]
Right now it's not possible to look at cross streets to orient yourself while looking at geographies, which will definitely come into play with block groups. Given the map layer we're using is really minimal, it might be worth raising the transparency significantly

**Comment by Lane** [comment]
I think we might be better off moving those street layers above the choropleth layers and setting them as semi-transparent, instead of adjusting choropleth transparency.

**Comment by pjsier** [comment]
We'll probably need to keep tweaking this, but closing the issue for now
