### ISSUE TITLE
Adjust "parent location" value for block groups and tracts

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#241]
For block groups and tracts set the parent location to `{{county}}, {{state}}`, to allow the user to identify location of the block group / tract when viewing in the data panel.

**Comment by pjsier** [comment]
Tracking this in https://github.com/EvictionLab/eviction-lab-etl/issues/54 but we can leave it here as well since we're managing most of the project issues here

**Comment by pjsier** [comment]
Fixed in the other repo
