### ISSUE TITLE
Add demographic stats to panel cards

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#261]
Allow "groups" of stats for location cards, and create a group to display demographic data as shown in the mockups:

![image](https://user-images.githubusercontent.com/21034/33644844-a894fe88-da04-11e7-83ed-b346baa90e1c.png)

**Comment by pjsier** [comment]
This is a minor thing, but would that category be "Demographic Breakdown" or "Racial/Ethnic Breakdown" if we're only including race/ethnicity stats in it? And would we have another subgroup for economic categories? This may be a question for design, but wanted to flag it here

**Comment by Lane** [comment]
Going to leave it as "Demographic Breakdown" for now and we can ask the research team next week based on Abby's response in Slack:

> I haven’t been informed of any changes to the labels or content related to what data we will have. I would prefer to leave that decision to the research team since “Racial/ethnic breakdown” could be problematic. Race/ethnicity are contained within “demographics”, which may be a more neutral term.
