### ISSUE TITLE
Show streets earlier?

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#286]
We start displaying streets at zoom 12, but we got some questions about people being able to orient themselves in the tract layer before that. It might be worth looking into displaying a more limited subset of streets earlier (zoom 10?)

**Comment by Lane** [comment]
Yeah, I think this is a good idea for sure.

I think showing markers (and *maybe* labels) for cities might also help users orient themselves.

**Comment by pjsier** [comment]
Great, should we start with zoom 10 for now and see how it feels?

I'm still worried that adding markers is going to be more confusing, but I like the idea of pulling labels in earlier if we filter for the largest populations. What do you think about that?

**Comment by Lane** [comment]
Yep, I like that.

I think markers could work if they're a unique shape (not circles).  If we only show city labels we'll have to go with some alternate text treatment so they are not confused with any visible choropleth labels.

**Comment by pjsier** [comment]
Closed unless we decide to bring them up higher (maybe just highways?)
