### ISSUE TITLE
Scroll hint on mobile

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#289]
This could be worth testing, but I've noticed with a couple people (and I think we heard during the meeting) that it's not immediately clear that you can scroll down the page on mobile once you've selected a location. It could be helpful to add some kind of visual cue that scrolling is possible, but not sure what that would look like since our space is limited

**Comment by Lane** [comment]
I think this would be helpful.  A couple options could be:

- Add a line of text directly below the horizontally scrollable cards that says "scroll down for more"
- Add some helper text at the very end of the horizontally scrollable area after the last card that says "scroll down for more"

-

**Comment by Lane** [comment]
Sounds like this is good design-wise, but we want it to show when they are viewing the map and hide when they start scrolling.
