### ISSUE TITLE
Rotate cards out instead of throwing error on selection past 3

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#290]
It was mentioned at the meeting that people would have preferred for the first card to be dropped (with some kind of animation) and a new one added if a user clicks on a map feature when they already have 3 cards selected.

This makes sense, but it's also worth considering how/if this would affect the "add a location" data cards and other parts of the tool

**Comment by Lane** [comment]
General consensus is that this is not a good thing.  Leaving prototype available here: http://eviction-lab-prototypes.s3-website.us-east-2.amazonaws.com/card-swap
