### ISSUE TITLE
Social share for graph image

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#291]
There's a potential interest in automatically including an image of the graph the user is looking at for social share directly in the post, rather than having someone screenshot it. We'll have to look and see if this is possible

**Comment by Lane** [comment]
Just to add to this a bit, Matt had mentioned he is hoping the user can choose one of the following to share for the selected locations:

  - Map
  - Bar Graph
  - Line Graph

It's unlikely we can pull this off, but I told him we will look into it.

**Comment by pjsier** [comment]
I think it's pretty safe to say this isn't possible at this point. Looked through the Twitter and Facebook APIs again, and neither one has any parameter for uploading an image through the API. The only way to do it would be to set the open graph metadata dynamically, but that would require server side rendering which we're not doing because Facebook (and likely Twitter, but didn't confirm) doesn't parse any JavaScript when pulling the metadata.

We could potentially look into making it easy for people to download the image, but I would imagine most people would just screenshot and may even not see a download button
