### ISSUE TITLE
Add "Start Here" tooltip on desktop as well

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#296]
Research team feedback:  The tool should have an indicator, the same as mobile, to direct the user on where to begin building out the map layers.

**Comment by pjsier** [comment]
There isn't an immediate parallel to the map layer selector on mobile since that contains all of them, but I'll assume the eviction layer makes the most sense as a starting point for now

**Comment by pjsier** [comment]
Closing if the tooltip location works
