### ISSUE TITLE
Rework file download dialog

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#297]
There was a request to add additional information to the file download dialog to clarify what is included in the files and also potentially adding more formats (CSV, DOCX).  I'm thinking a good approach for this is to have a 3-step dialog with something like:

> Note: someone else should write the copy, this is just to show structure.

Step 1: Select type of export
---
**Spreadsheet**
Export a spreadsheet of `{{locations}}` for the years 2000 - 2016 including eviction, census, and ACS data.

**Document**
Export a document that includes and overview of evictions in `{{locations}}` and issues related to evictions. 

**Presentation**
Export a presentation with slides for `{{locations}}` including maps and graphs.

> If user selects an option with multiple file types (e.g. CSV, and XLSX) go to step 2.  If there is only one file type, go to step 3.

Step 2: Select file type
---
**Excel (.xlsx)**
Download the spreadsheet for Microsoft Excel.

**Comma Separated Values (.csv)**
Download the spreadsheet in comma-separated format.

Step 3: Download your file
---
Your export is being created...

> File begins downloaded when ready and dialog is dismissed.

I'm also leaning towards not using a form here, the user just clicks on the type of file and is moved to the next step.  Needs discussion with the team before implementing.

**Comment by pjsier** [comment]
I like this a lot overall, but it seems like we don't need to make it into multiple steps if the only difference in step 2 is Excel vs CSV. I think we could just have those as two separate options (with similar descriptions), and keep the overall structure as-is

**Comment by Lane** [comment]
Good point, could definitely get rid of step 2.

**Comment by pjsier** [comment]
I'm remembering some conversations about including text at the top indicating what data the export would be for? I think it was something along the lines of "Generate a file export for Colorado, Michigan, and California data between 2000 and 2016." Making a note here so we don't forget
