### ISSUE TITLE
Card not displayed when clicking

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#299]
Not sure if this was a network issue or what, but one of the cards would not show in the Princeton meeting when Matt was clicking on it.

I think we should adjust how the card is added so that it shows up immediately, and then the cards fill out as the Observables emit the data.

**Comment by pjsier** [comment]
I hadn't actually looked at this issue before, but I like the idea of showing the card immediately. We could do the same thing with the outline now by using the bounds the way it does when loading from route parameters. Would we show "Loading" under each stat, or just show the labels with the values empty?

**Comment by Lane** [comment]
Thinking through it some more, I don't think we would need to have "Loading" or empty values.  We have all of the data immediately available to show the card with the data when they click on the feature, but it waits until the data for all of the years is fetched before displaying it.

When loading locations from route parameters, I think it's fine to wait until the data for all of the years has been retrieved before showing them.

**Comment by Lane** [comment]
Would also be good to have some sort of error handling so that a toast message is displayed if there is a problem fetching the data for a card.

**Comment by pjsier** [comment]
Ahh good point, makes sense to me!
