### ISSUE TITLE
Default, minimum zoom on mobile should be lower

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#300]
The current default/minimum zoom on mobile don't allow for the full continental US to fit in the viewport, so we should at least allow people to zoom out more

**Comment by pjsier** [comment]
We would have to update the `style.json` file as well as the layer parameters for this. Counties should still probably be visible, but we'll have to tweak the parameters

**Comment by Lane** [comment]
Could we fix this by removing `minZoom` from the MapboxGL config and specifying a `maxBounds` that is a bounding box around the United States instead?

**Comment by pjsier** [comment]
That should work, mainly just wanted to note earlier that we'll need to update the zoom scaling throughout

**Comment by pjsier** [comment]
So I didn't realize it earlier, but our minimum zoom is actually set to 3, so we can change it to 2 without having to update anything in `style.json`. I tried the `maxBounds` setting, but because of Alaska and Hawaii the bounds are so wide that it's pretty impractical
