### ISSUE TITLE
Very long place names still overflowing

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#302]
Not sure how much we can do about this one, but wanted to include it here 
<img width="223" alt="screen shot 2017-12-18 at 6 36 15 am" src="https://user-images.githubusercontent.com/8291663/34106445-d7c9c0a4-e3bd-11e7-99fa-f38b00974151.png">

**Comment by pjsier** [comment]
I can also research some of the "Consolidated Government" ones and see how important it is to keep that full label. If it seems like we can drop it I would definitely prefer doing that

**Comment by Lane** [comment]
Yeah, I think that's a good solution if it's okay to drop that.  If we need to keep it in there for some reason I think we can just add some styles to truncate it, as I'm guessing there are not too many of these.  (Correct me if I'm wrong)

**Comment by pjsier** [comment]
There aren't a ton for sure, and I'm gonna go through all of the names now and see what the longest ones are, as well as if they have any common suffixes. That one specifically shows up in searches for "Augusta-Richmond County", even though it's a city, so I'll drop "Consolidated Government" here and probably anywhere else I find it

**Comment by pjsier** [comment]
Closing this and opening it in the ETL repo instead
