### ISSUE TITLE
Theme raw data interface

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#315]
The S3 data interface should be themed for launch.

**Comment by pjsier** [comment]
On the one hand it seems like overkill to split this into a separate repo since it's one file, but on the other it doesn't really fit anywhere else. Does that work? I'm just gonna base it off of the one we're currently using https://github.com/awslabs/aws-js-s3-explorer

**Comment by Lane** [comment]
Yeah splitting into a separate repo is fine with me.

**Comment by pjsier** [comment]
Current example is here http://eviction-lab-public-data.s3-website-us-east-1.amazonaws.com/ and the source repo is https://github.com/EvictionLab/aws-js-s3-explorer

**Comment by pjsier** [comment]
Based on design feedback, all we need to do here is capitalize state names and add some navigation for going back to the main page. I'm thinking I'll just make the `eviction-lab-public-data` text a link to the main page
