### ISSUE TITLE
Data upload via CMS interface

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#316]
Provide an input that allows someone to upload a new data file that triggers a build of new map tiles and eviction rankings with the new data.

Would likely want some kind of staging environment for this, just in case someone uploads bad data.

Not a high priority, could probably wait until post launch if extra time is needed.

**Comment by pjsier** [comment]
Guessing we'll want to delay this until after launch

**Comment by Lane** [comment]
Yeah, going to close this.  Can move it to the website repo
