### ISSUE TITLE
Setup Travis CI for Eviction Lab website

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#332]
Add Travis CI build to eviction-lab-website repository to build and push to S3 on all branches, and to invalidate the website cloudfront distribution on pushed to master.

**Comment by pjsier** [comment]
Will be closed by https://github.com/EvictionLab/eviction-lab-website/pull/76

**Comment by Lane** [comment]
Dropping this, can be tracked in the website repo now that we're using that
