### ISSUE TITLE
Loading indicator doesn't show as expected

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#336]
Noticed this while refactoring, the loading indicator doesn't show as expected.

If I zoom or move around where some geography the loading indicator doesn't show.  Sometimes it shows momentarily, but it seems inconsistent.

![no-loading](https://user-images.githubusercontent.com/21034/34279626-549d5b64-e66f-11e7-9b2e-891a0ee9c0fa.gif)

**Comment by pjsier** [comment]
It could have something to do with the event we're using to trigger changes in the map loading, `render`. It gets set here, and I think we had tried other ones https://github.com/EvictionLab/eviction-maps/blob/development/src/app/map-tool/map/mapbox/mapbox.component.ts#L105

Did it show up like this before the refactor?

**Comment by Lane** [comment]
Yep, the gif is from the S3 preview before the refactor.  Had to go check that to make sure.

**Comment by pjsier** [comment]
On second thought, this may have to do with the fact that we're debouncing every half second, which is slower than it was initially. When I do those same actions, but with larger gaps in between, I see the loading indicator

**Comment by Lane** [comment]
This is 99% fixed, but there are a couple things that would be good to fix up before launch if possible:

- Loading indicator flashing on hover.  I get this is a render event, but it's so minor and having the loading indicator flashing a bunch as you're moving the mouse can be really distracting.
- Loading indicator flashing after page load -- Can only reproduce on Ubuntu Firefox 57.01 so far, usually after loading a link from a route.  Happens about 50% of the time.

![load-flicker3](https://user-images.githubusercontent.com/21034/34304460-1bf77eec-e6f7-11e7-9ac6-1950e9360480.gif)

**Comment by pjsier** [comment]
Some additional notes here, we may be able to use the `dataloading` and `data` events separately from the render event, and potentially debounce the render event more aggressively

**Comment by pjsier** [comment]
Closed to the extent that we can fix it, since updating the hover layer is still a data update event
