### ISSUE TITLE
Line chart tooltips use wrong colors

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#360]
Tooltip colors are based off of index and not which line they're associated with

<img width="867" alt="screen shot 2017-12-28 at 10 09 02 pm" src="https://user-images.githubusercontent.com/8291663/34428551-03fb5654-ec1c-11e7-9bd7-a30998e04997.png">

**Comment by pjsier** [comment]
This was caused by https://github.com/EvictionLab/angular-d3-graph/pull/7/. Now that we're only emitting line data for lines with values, DOM elements are no longer created for each line, so the `nth-child` styling breaks. We could either emit `null` from the graph module, or find some way of determining which line goes with which tooltip

**Comment by Lane** [comment]
I think having a hidden empty div when there is no value for the given line should be fine.

**Comment by pjsier** [comment]
This probably closed automatically, but we still need to merge #389
