### ISSUE TITLE
Use same styling for bar and line chart year selects

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#374]
Just noticed that the year select for the bar chart and line chart look different, but the style for the line chart would probably work for both. The bar chart selector looks misaligned, is there a reason for keeping it that way or could we make it display the same way as the line chat select boxes?

Current:
<img width="1134" alt="screen shot 2018-01-06 at 7 39 24 pm" src="https://user-images.githubusercontent.com/8291663/34645672-7bf88808-f319-11e7-9e12-3334b0751e67.png">

With year styling:
<img width="1132" alt="screen shot 2018-01-06 at 7 39 10 pm" src="https://user-images.githubusercontent.com/8291663/34645673-81522214-f319-11e7-8015-415c8e1c5b41.png">

**Comment by Lane** [comment]
Not sure if I'm following.  Are you referring to the "Displaying year" text being out of alignment?  If so, then yes that is a bug and it should be aligned with the select box text.

Or are you saying we should have a single "year" select box for line charts instead of the start / end selects?

**Comment by pjsier** [comment]
I'm saying the "Displaying year" text is out of alignment, and the border might not be necessary (unless we want to add it to both)

**Comment by Lane** [comment]
Ah gotcha.  Yep, it should be as it looks in the second screenshot.  I must have introduced some conflicting CSS when building the ranking page that messed it up.
