### ISSUE TITLE
Implement main menu

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#380]
The menu is currently semi-functional, and not implemented on mobile

**Comment by Lane** [comment]
Still not sure on design for this, I think it was something that was going to be tested.  Marking as design needed.

**Comment by pjsier** [comment]
Is this closed by #484?

**Comment by Lane** [comment]
Yep.  Still some minor things to do (translation, accurate links) but those will come once we have the content, translations, and links defined.
