### ISSUE TITLE
Toast improvements

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#381]
This may not be needed, but the toast service through `ng2-toastr` has a couple potential issues.

- [x] It only shows up on the top of the screen, so you don't see error messages if you try to add an existing feature from the location cards, for example. We should probably change that to `position: fixed`
- [ ] It currently doesn't dismiss on click, which becomes more of an issue if we have it display at all scroll positions
- [ ] The error icon looks blurry on retina screens. This isn't a big issue, and it may be preferable to remove the icon(s) in toast notifications altogether

If you've got any different thoughts on this feel free to dismiss any of these, but I wanted to make sure we have it recorded somewhere

**Comment by Lane** [comment]
Yep, these should be implemented.  I threw it in with the default styling because there was some talk about testing / moving it somewhere else, not sure where we're at on that.

Can pass options for dismiss on click: https://github.com/PointInside/ng2-toastr#toastoptions-configurations

**Comment by pjsier** [comment]
Position is already fixed, but I got confused because it's not currently an error to add a location that is already in the cards. Not sure that's a priority anyway, and it could get difficult since we're allowing for updating existing data
