### ISSUE TITLE
UI Autocomplete Component

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#39]
Used for:
  - Predictive Search: [Functional Spec](https://docs.google.com/document/d/1_20EvW4w73O-yjt22THLxGh1b6rTe-cyF2ZZXfLnUvk/edit#heading=h.406bzdj0qjh2)
  - Location Comparison: [Functional Spec](https://docs.google.com/document/d/1_20EvW4w73O-yjt22THLxGh1b6rTe-cyF2ZZXfLnUvk/edit#heading=h.b8c6gpsfl22r)

Todo:
  - [x] Accepts input of data available for search
  - [x] Accepts input value for the limit of suggestions to show
  - [x] Accepts input of the property name to match on each item in the data
  - [x] Displays top matches in data when user types a value
  - [x] Emits selected value when suggestion is selected
  - [x] Mouse bindings
  - [x] Default style / theme variables
  - [x] Keyboard bindings
  - [x] Touch bindings
  - [x] Displays an "X" on the right side of the input when typing that clears any input when pressed

**Comment by pjsier** [comment]
To clarify on this, since we're using a pre-built component, do we need to re-create the bindings or modify them in any way? I'm using the built-in `typeaheadOnSelect` which looks like it covers any kind of bindings we would need.

**Comment by Lane** [comment]
Nope, all good as long as the bindings behave as what's described in the functional spec.
