### ISSUE TITLE
Cards overflowing horizontally on desktop displays in data panel

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#397]
On `.gt-tablet` resolutions up to ~1180px, the `min-width` on location cards are causing a horizontal  overflow.  We should avoid horizontal overflow on desktop displays.

Need to find a fix that solves #364 but also doesn't cause horizontal overflow.

**Comment by pjsier** [comment]
Could we add an additional breakpoint for this case since it's for a narrow range?

**Comment by Lane** [comment]
I think we should adjust the cards so the "add location" card doesn't show up until the other card has transitioned out.  Then we can have fluid widths that cover several breakpoints without having to worry about the cards getting squished and pushing the page layout around.

**Comment by pjsier** [comment]
That makes sense to me. I looked into that initially, but it means we'd have to put `ngIf` on some kind of delay so I tried the `min-width` fix first

**Comment by Lane** [comment]
I think we should be able to do it with state changes in the animations on the component.  Not 100% sure though.
