### ISSUE TITLE
Add year labels to marker, left, and right on slider

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#412]
Update slider component to have left / right labels for min and max values.  Add current value as a label on the scrubber.  Drop the hover label.

![image](https://user-images.githubusercontent.com/21034/34803529-05d3aca0-f631-11e7-8ea6-64c93e4845df.png)

**Comment by Lane** [comment]
After discussion, desire mobile behaviour is:
- Show tooltip on drag
- Label one side of slider (I think left side makes sense, if we're putting the marker at the latest year by default)

**Comment by pjsier** [comment]
Does this mean we should hide the tooltip on drag for desktop?

**Comment by Lane** [comment]
I think it's fine to have while dragging on desktop, but we'll want to drop displaying it on hover.
