### ISSUE TITLE
Map Zoom Slider

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#42]
[Functional Spec](https://docs.google.com/document/d/1_20EvW4w73O-yjt22THLxGh1b6rTe-cyF2ZZXfLnUvk/edit#heading=h.13jv3h7l1jmc)

Todo:

  - [x] Implement using Mapbox default +/-

**Comment by Lane** [comment]
Updated to switch implementation to mapbox controls.

**Comment by pjsier** [comment]
Can we close this after #67?
