### ISSUE TITLE
Update eviction stats in data panel cards

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#432]
First two stats on data panel cards are "Eviction Rate" and "Evictions", but should be "Eviction Rate" and "Evictions Per Day".  Eviction rate should also show a comparison to US average.

![image](https://user-images.githubusercontent.com/21034/34898030-3934e752-f7ae-11e7-9b73-d08a03dbddd2.png)

**Comment by pjsier** [comment]
Just added a US average data creation step, so we can load it similarly to the rankings. It's at https://s3.amazonaws.com/eviction-lab-data/avg/us.json, and it's just the eviction properties by year
