### ISSUE TITLE
Eviction Map

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#45]
[Functional Spec](https://docs.google.com/document/d/1_20EvW4w73O-yjt22THLxGh1b6rTe-cyF2ZZXfLnUvk/edit#heading=h.39kej142bb3x)

Todo:

- [x] Map is implemented using UI Map Component
- [x] Map shows choropleth based on data value selected in Data Highlight Select component
- [x] Map shows data level (state, city, county, etc) based on selected  Data Level Select component
- [x] Map shows bubbles over selected data level sized and shaded based on eviction rate
- [x] Map auto selects data level based on zoom level, unless otherwise specified.
- [x] Map boundaries have active states when selected or hovered
- [x] Add UI Progress component that displays during long map operations
- [x] Tooltip displaying location
- [x] Map displays either eviction filings or judgements based on eviction type toggle value
- [x] Map shows data card when map feature is clicked 
- [x] Map labels are filtered by population at lower zoom levels
- [x] Treatment for areas with no data
- [x] Implement map style

**Comment by pjsier** [comment]
I think we've mentioned this, but it could be good to add some kind of loading animation between layers switching. I've noticed that on Firefox it's a second or so slower

**Comment by Lane** [comment]
Definitely.  I will add a loading service task to Milestone 2.

**Comment by Lane** [comment]
Added the progress component to Milestone 1, then added a task for this component to add the progress component to display when loading.
