### ISSUE TITLE
Select dropdowns should scroll when selecting item with keyboard

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#460]
When using the keyboard to select an item in a dropdown with many items, the list of items should scroll so the highlighted item remains in view.

Currently the list does not scroll and the highlighted item goes out of view:

![select-out-of-view](https://user-images.githubusercontent.com/21034/35016799-6f86ce66-fad7-11e7-9cf1-f2b585c7a851.gif)

**Comment by pjsier** [comment]
Is this related to #442?

**Comment by Lane** [comment]
Nope, I have a fix for #442 in the branch I'm working in right now
