### ISSUE TITLE
Add US average to graphs

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#463]
Not sure what was settled on, but adding the US average as a point of comparison has come up a few times

**Comment by Lane** [comment]
I think we had decided US average would be shown in the cards for sure, as mentioned in #432.

I'm not sure if we reached a decision on the graphs, so I'll post on slack to confirm.

**Comment by Lane** [comment]
Okay, looks like we want it in the graph as well.  US average in the graph will have a bit different behaviour from the other locations:

- Color is fixed, tentatively to #94AABD with a gradient from #C6D5E0 to #94AABD for bars (need confirmation from Noele)
- Clicking the dismiss button on US Average rotates the "X" button into a "+" button, and drops the opacity of the marker and text to 0.5

**Comment by Lane** [comment]
Noele has confirmed that the colors above are correct.
