### ISSUE TITLE
Locations in URL params don't retain order on refresh

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#464]
Not sure if this is even an issue, but for some reason locations don't stay in the same order they were added on refreshing the page

**Comment by Lane** [comment]
I think this is fine for now.  If we have some spare cycles towards the end I'd say it's worth fixing, but not essential.

**Comment by Lane** [comment]
Taking a second look at this, I don't think it matters.  Good to close, unless you can think of a use case where it needs to be in the same order.

**Comment by pjsier** [comment]
I can't think of any cases where it would actually change anything, so I'll close it
