### ISSUE TITLE
Mobile menus broken

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#474]
The Map submenu no longer opens, and tapping Search pushes the menu icons down, and puts the search nav above them

The Map submenu opens at a mobile screen size on desktop, but not on mobile devices, which makes me think it has something to do with touch events. The Map submenu bug doesn't affect `master` currently, but the Search position bug does.

Map bug was introduced some time between bbc6524 and 29c79aa, and Search bug was introduced between de6c1b4 and 6c886c7

**Comment by Lane** [comment]
Whoops, I think I did this when shifting the DOM around for proper ordering.  Will fix this up with the menu implementation today.
