### ISSUE TITLE
Eviction Type Select

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#48]
[Functional Spec](https://docs.google.com/document/d/1_20EvW4w73O-yjt22THLxGh1b6rTe-cyF2ZZXfLnUvk/edit#heading=h.y4qvtopfqm39)  

Todo:
  - [x] Determine if implementation will use UI Toggle or UI Select
  - [ ] Style to match mockups
  - [ ] Update map with filings / judgements when value is selected

**Comment by pjsier** [comment]
I think we were leaning toward doing this as UI Select because there isn't a lot of value in making it different than the other options, and because we want to be able to leave it empty by default (at least that's my understanding from user testing). If so, all of these are covered by #45

**Comment by Lane** [comment]
Yep I think we are for sure using a select for the map, but there's also been some talk about adding a toggle to the data panel?  We'll need to check in with Abby / Noele and see what the plan is.

**Comment by pjsier** [comment]
Ahh got it, so this is issue is just for the graph? I thought it was for both for some reason

**Comment by Lane** [comment]
For both, the map toggle is done, but we might need one for the data panel as well.
