### ISSUE TITLE
Year Slider Lags

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#495]
Year slider lags when dragging.  Need to determine the expensive function calls and debounce those.

![slider-lag](https://user-images.githubusercontent.com/21034/35176122-7a61db14-fd34-11e7-84cf-214f65999274.gif)

**Comment by pjsier** [comment]
This looks like `mousemove` for sure and potentially `touchmove`. I can make this update

**Comment by Lane** [comment]
Closed with #497
