### ISSUE TITLE
Year slider not triggering map updates

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#498]
This might be related to #497, but moving the year slider no longer updates the map. Data attributes in location cards still seem to be updated though

![year-slider-map-bug](https://user-images.githubusercontent.com/8291663/35186363-8b0268cc-fdd8-11e7-8622-15474df20f6b.gif)

**Comment by Lane** [comment]
Whoops... the debounced function must not be getting called.  I'll take a look and see why.
