### ISSUE TITLE
File Download Modal

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#50]
[Functional Spec](https://docs.google.com/document/d/1_20EvW4w73O-yjt22THLxGh1b6rTe-cyF2ZZXfLnUvk/edit#heading=h.7ai86251jbsm)

Todo:
  - [x] File download modal opens when pushing download button
  - [x] File download modal has checkboxes for which filetypes to download
  - [x] Has dismiss button in top right
  - [x] Has "Download" and "Cancel" buttons

**Comment by pjsier** [comment]
Will there be anything about previewing the exports here? This is more of a UX question, but I'm curious how we'll make clear to people what they're downloading with each file type, given that the PowerPoint is very different from the Word doc and Excel sheet.

**Comment by Lane** [comment]
A preview would be nice for sure. I'll add a comment in the Functional Spec to get Abby's input on it.
