### ISSUE TITLE
Use us-cities-10 source for city labels

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#502]
City labels are currently being sourced from OpenMapTiles, but that's leading to some weird inconsistencies where mid-sized cities in their data aren't represented in our census information:

<img width="532" alt="screen shot 2018-01-22 at 8 40 39 am" src="https://user-images.githubusercontent.com/8291663/35226153-0d6ca174-ff50-11e7-8741-9618fdb5b8a1.png">

We should be able to switch to using the `us-cities-10` layer and filtering based off of the population as a rough proxy so that labels line up

**Comment by Lane** [comment]
I was going to use the us-cities centers layer for the labels, but realized we only have eviction rates as properties on those layers, so we'll need to add population in the properties if we want to use this.  Or we could add rank the same way openmaptiles does.

**Comment by pjsier** [comment]
Ahh good point, I forgot about that. I'll update the ETL repo to add population, since we're not sure when we'll get the rankings used in city ranking (which would seem to make the most sense otherwise)

**Comment by pjsier** [comment]
Just updated, once it finishes building we'll have the `p-10` data property available to use
