### ISSUE TITLE
Embed as iframe share option

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#509]
We've been thinking of making an option to embed the current map view as an `iframe` so that smaller news outlets and sites could pull a customized view directly into their content (I've seen it done with CARTO and Mapbox maps before).

It could exist as an additional option in the share menu, or it could potentially be a sub-option on the share a link popup. Either way, we'd likely need to highlight it somewhere that's more media-focused since I don't imagine people will be looking for that on their own.

We could trigger the `iframe` view with a URL parameter that limits the view, potentially removing most/all controls for changing the map data since the `iframe` will probably be a much smaller size.

**Comment by pjsier** [comment]
It sounds like there's an interest in doing this, so I got a head start on a simplified UI in the `feature/embed` branch. I just added a query parameter `embed` that triggers a class on the root component

Here's the current view:
<img width="822" alt="screen shot 2018-01-24 at 9 10 09 am" src="https://user-images.githubusercontent.com/8291663/35339567-8913a632-00e6-11e8-8dc1-0c73efd04c64.png">

Some things to consider:
* I removed all controls with the idea that someone would be sharing a specific view (and that it'll be using significantly less space), but do we want to leave some controls in there?
* If we remove controls for a more stripped down look, we'll need to add more information to the legend including the name of the layer outside of a tooltip and a bubble legend
* Should we include any part of the location card interaction at all? My initial instinct was no, so I removed it here, but that's open for discussion. Maybe the hover tooltip could have more information?

**Comment by pjsier** [comment]
Pulled from @lane's PR comment, but it's worth looking into whether it makes more sense to set this up as a separate route entirely rather than a URL parameter in refactoring

**Comment by pjsier** [comment]
NPR's [Pym.js](http://blog.apps.npr.org/pym.js/) would be useful here, and I've seen other organizations use it for embedding widgets

**Comment by Lane** [comment]
Wouldn't Pym.js be something that is included on the page hosting the iframe, or am I reading this wrong?

**Comment by pjsier** [comment]
It's both, here's an example from ProPublica https://www.propublica.org/nerds/illinois-governor-race-campaign-finance-widget-2018

**Comment by Lane** [comment]
Ah, gotcha.  Makes sense!  haha... appreciate they have a `/nerds` section.
