### ISSUE TITLE
Email Share Modal

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#51]
[Functional Spec](https://docs.google.com/document/d/1_20EvW4w73O-yjt22THLxGh1b6rTe-cyF2ZZXfLnUvk/edit#heading=h.wjsx4b34jagw)

Todo:
  - [ ] modal opens when pushing email button
  - [ ] modal has checkboxes for which filetypes to download
  - [ ] modal has an input field for email address
  - [ ] Has dismiss button in top right
  - [ ] Has "Send Email" and "Cancel" buttons

**Comment by pjsier** [comment]
Will we actually be sending emails or will this be some kind of wrapper/UI around a `mailto` link or are we actually setting up emailing from SES or something similar?

**Comment by Lane** [comment]
It's looking like we will need to setup emailing.

**Comment by Lane** [comment]
Switching to `mailto` for emails.
