### ISSUE TITLE
Slider jumping

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#518]
Slider sometimes emits an incorrect value, causing the marker to "jump"

![image](http://g.recordit.co/wFJjlqRKNu.gif)

**Comment by Lane** [comment]
Can't see it very well in the gif, but if you slowly drag the slider you'll see it.

**Comment by pjsier** [comment]
I've noticed this before, especially on mobile. Could it be because of the debounce time?

**Comment by Lane** [comment]
I don't think we're debouncing any events on the slider, just the handler for when the values change so that shouldn't effect anything.  Looks like we're setting the position of the slider from within the component and also from a double binding on the value input, so I'm thinking that's probably the cause.

**Comment by pjsier** [comment]
I'm still getting this a bit on mobile? Reopening for now just in case

**Comment by Lane** [comment]
iOS Chrome for this one too?  Not seeing it in Android Firefox / Chrome.

**Comment by pjsier** [comment]
Yep, still coming from iOS Chrome here. It doesn't happen as much as it used to, but I'll still get periods where I stop sliding and it jumps back

**Comment by Lane** [comment]
Ah, gotcha.  It is setup so that it snaps to the closest year position when released.  Is that what you're seeing, or is it happening while dragging?

**Comment by pjsier** [comment]
Yeah it's only on release, never while dragging
