### ISSUE TITLE
UI Progress Component

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#52]
A component that is used to display progress of a task, or plays an animation for actions of  indeterminate time.

  - [x] Accepts input of progress amount (0 - 1)
  - [x] Accepts boolean input for `loading`, which determines if the component is actively loading.
  - [x] Displays bar that fills a % corresponding to `progress` value
  - [x] Displays indeterminate animation if no progress is given.
  - [x] Default style / theme variables

**Comment by pjsier** [comment]
Are you thinking it would just be a loading bar with different animations for determinate and indeterminate, or would we have a bar and a spinner?

**Comment by Lane** [comment]
I think we'll need a bar for sure.  I'm thinking something we can tuck under a header when tiles / data is loading, like Github does. We might need a spinner too, I will check with Noele and see if she has a design preference.
