### ISSUE TITLE
Back to Map button flickers on iOS after clicking map selector

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#556]
After tapping the map button for the first time, the overlay and "Back to Map" button flicker on the page for a second or two. I think this showed up after #536, but not sure

**Comment by Lane** [comment]
Hmm.. I can't replicate this on Android Firefox/Chrome or emulated through the browser.  Sounds like maybe the page scrolled a bit?

**Comment by pjsier** [comment]
That's weird, this happens to me every time on iOS Chrome. The scrolling would make sense, but not sure why it would only happen there

**Comment by Lane** [comment]
Ah gotcha, will check it out on iOS simulator next time I'm on my mac.

**Comment by pjsier** [comment]
Ok, reproduced this in BrowserStack with Safari, as well as locally with Safari. It sounds like it's limited to iOS, so I updated that as well. Here's what I'm seeing:

![map-flicker](https://user-images.githubusercontent.com/8291663/35700750-7c3966e4-0759-11e8-87e8-c6c8e1ea5269.gif)

**Comment by Lane** [comment]
Ah yes, was able to replicate in simulator too.  Definitely cause by "Selecting map in the toolbar should scroll back to the top" in #536.  Will fix this up today.
