### ISSUE TITLE
Graph hover tooltips jumping

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#563]
It doesn't show up when I record a GIF, but it looks like the graph hover tooltips are jumping a bit like they were before we initially added the debounce. Was that changed in the data panel refactor?

**Comment by Lane** [comment]
I did drop the debounce time a bit because the tooltips seemed to be lagging behind a bit.  I'm not noticing any jumping on my end.  Could you do a quick video capture with quicktime?

**Comment by pjsier** [comment]
I can't replicate it now, so it may have just been a caching issue. The reduced debounce looks good!
