### ISSUE TITLE
Bubble legend included somewhere

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#568]
I know we had talked about putting this in help, but since it isn't in the current design and since we have some extra time I wanted to raise it here.

We'll probably need to include a bubble legend for the embed component since we won't have the space for location cards, so it might be worth considering adding it to the general map. Maybe something like this, where it's just two bubbles (changing size instead of color) on the left side of the current choropleth legend?

<img width="315" alt="screen shot 2018-02-06 at 7 56 38 am" src="https://user-images.githubusercontent.com/8291663/35863157-62214002-0b13-11e8-8f99-3a49deade260.png">

Here's another option that's really simple and compact, and used in a similar context

<img width="439" alt="screen shot 2018-03-17 at 4 50 03 pm" src="https://user-images.githubusercontent.com/8291663/37560275-420403fe-2a03-11e8-97aa-b4ce9ceda232.png">

**Comment by pjsier** [comment]
One resource on this since it'll have to be updated dynamically https://www.mapbox.com/help/gl-dds-map-tutorial/

**Comment by pjsier** [comment]
@james-minton this has been on the backburner, but it looks like we'll need it

**Comment by noelelusano** [comment]
@pjsier @james-minton working on this; given the amount of stuff in the UI will need some focused time today to iterate on it.

**Comment by noelelusano** [comment]
![image](https://user-images.githubusercontent.com/6036323/37687132-9ddf439a-2c57-11e8-9fbf-e2d9df34862f.png)

• please go by the sketch file as fonts vary between numbers and text.
• spacing is in increments of 8 as much as is possible.
• i've eliminated all letter-spacing on numbers and text here.

sketch:
https://app.box.com/s/go5r2dyjb3uqeu64dhw0qqmhin7bbmin
(under "Symbols - Legends")

**Comment by pjsier** [comment]
Closed by #861
