### ISSUE TITLE
Add "View location in map" link to rankings data panel

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#586]
Add a "View location in map" link to ranking data panel:

![image](https://user-images.githubusercontent.com/21034/35948249-f6a6eba8-0c28-11e8-987d-8437436b5fd9.png)

**Comment by pjsier** [comment]
Based off of the conversations yesterday, is this still happening?

**Comment by Lane** [comment]
Not sure, will check in.

**Comment by pjsier** [comment]
Closing based on feedback
