### ISSUE TITLE
Style link share popup

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#592]
Link share popup still has default styles, not sure if we need designs on this or if we can just base it off of the modal styles for now

<img width="349" alt="screen shot 2018-02-07 at 6 19 31 pm" src="https://user-images.githubusercontent.com/8291663/35948718-9507a86e-0c33-11e8-83af-a0598e072728.png">

**Comment by Lane** [comment]
Closing this, we are using the same styles as the dialog window now.  Will be cleaned up a bit more by #674
