### ISSUE TITLE
counties.csv loading twice

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#632]
I'm seeing the `counties.csv` file loading twice on page load.  Might be happening if the search service is loading this file, because it gets instantiated every time we use the `location-search.component`.  For optimization, we should adjust so that the CSV is only loaded once.

![image](https://user-images.githubusercontent.com/21034/36316273-232c2aec-12f7-11e8-990b-873743ac49a0.png)

**Comment by pjsier** [comment]
Based on conversation in Slack, the way we're handling this is to have the search service in the common `services.module`, and then have the `app.component` load the search data and provide it to the component based on which route is activated
