### ISSUE TITLE
Multiple favicon requests

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#635]
Getting a lot of HTTP requests for the same favicon, should try and limit it to one request so that these requests don't block other requests.

![image](https://user-images.githubusercontent.com/21034/36317588-b681d37a-12fa-11e8-88f9-de81000757b4.png)

**Comment by Lane** [comment]
I just noticed that the majority of these request are coming from when I resize the window.  I am only getting 2 requests for each on page load, so maybe lower priority than I initially thought.

**Comment by pjsier** [comment]
I'm only seeing this on Chrome (also checked Firefox and Safari), and since it only happens on resize it looks like it might be intended browser behavior? I searched around a bit and haven't seen anything mentioning it to confirm that though

**Comment by Lane** [comment]
I'm not seeing this on resize with other sites, but not too concerned about this one since finding out it was only on resize.  I'll drop it into the backlog.
