### ISSUE TITLE
Only configure one instance of PageScrollService

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#638]
I'm getting the warning `An instance of PageScrollService already exists, usually including one provider should be enough, so double check.` when running the tests.

**Comment by pjsier** [comment]
This may actually just be an issue in the tests, but leaving this open until we can confirm that

**Comment by Lane** [comment]
Yeh, I'm playing around with this a bit right now.  Not seeing the warning in browser, so I think it is just in the tests.  Thought it'd be an easy fix for the tests, but I'm still getting it when removing PageScrollService from everything.  Tried using the `.forRoot()` declaration here: https://github.com/Nolanus/ngx-page-scroll/issues/96

but... still getting the warning.

**Comment by pjsier** [comment]
Honestly, if it's just a test issue I don't think it's worth fixing. If that works for you then we're good to close

**Comment by pjsier** [comment]
Closed by #642
