### ISSUE TITLE
Ranking UI panel updates

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#663]
- Drop "search" label above the search input
- Change "filter" label to "show rankings for"
- Add hints to dropdowns (still TBD, see sample below)

![image](https://user-images.githubusercontent.com/21034/36444858-a4202cc6-1639-11e8-996c-71d2acf2c9b2.png)

**Comment by noelelusano** [comment]
can we position the question mark icon as a floating element above search field?

![image](https://user-images.githubusercontent.com/6036323/36447652-d40d7484-1639-11e8-98d5-25d0d621b48a.png)

https://projects.invisionapp.com/d/main#/console/13309693/280456988/preview

**Comment by Lane** [comment]
@noelelusano we can, but a few things to note:

- We'd want 44x44px of space for the question mark to give a suitable touch radius
- There's potential that the user will trigger the dropdown when trying to view the hint or vice versa
