### ISSUE TITLE
Add heading to ranking list

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#664]
Ranking list should have a heading that follows the format:

Heading: "Top evicting {{ AREA }} in {{ REGION }}"
Subheading: "Ranked by {{ RANKING_PROPERTY }}" - subheading style to be provided by @noelelusano

Heading be styled to match mockups provided: https://projects.invisionapp.com/d/main#/console/13381916/279454603/preview

**Comment by noelelusano** [comment]
headings can be found in these mockups
1440 - https://projects.invisionapp.com/d/main#/console/13381916/279454603/preview
1024 - https://projects.invisionapp.com/d/main#/console/13381916/279454597/preview
768 - https://projects.invisionapp.com/d/main#/console/13381916/279454596/preview
320 - https://projects.invisionapp.com/d/main#/console/13381916/279454600/preview
