### ISSUE TITLE
Print Styles

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#668]
Add some print styles so that the map tool and rankings page are formatted in a readable way when printed.

**Comment by pjsier** [comment]
So here's a potential issue: http://fuzzytolerance.info/blog/2016/07/01/Printing-Mapbox-GL-JS-maps-in-Firefox/

Firefox will only print Mapbox GL maps if `preserveDrawingBuffer` is set to true, but we have that disabled as a performance improvement, and while we might be able to trigger the map to regenerate right before print with the parameter, it seems unlikely. It seems alright to just ignore the map for Firefox then?

**Comment by Lane** [comment]
Yeah, I'd say don't print the map on firefox.  Instead we should add a message saying something like "map printing is unavailable on this browser".

**Comment by pjsier** [comment]
Closed by #979
