### ISSUE TITLE
apply consistent box-shadow treatments across layered elements

### ISSUE THREAD

**Issue by noelelusano** [EvictionLab/eviction-maps#674]
specifics to come mid-march, here as a reminder

**Comment by Lane** [comment]
Took a quick inventory of our "elevated" elements. For the map it looks like we'll need 3 different shadow levels:

**Level 0 (no shadow)**
  - Map

**Level 1**
  - Map Zoom controls
  - Map Cards
  - Map Dropdowns
  - Time Slider
  - Data panel
  - View More Data / Back to map button (on map)
  
**Level 2**
  - Page Header
  
**Level 3**
  - Dialogs
  - Popovers (link share)
  - Page Menu

**Comment by noelelusano** [comment]
![image](https://user-images.githubusercontent.com/6036323/37844455-15c097ea-2e85-11e8-8763-01ffc9f88f0e.png)

![image](https://user-images.githubusercontent.com/6036323/37844588-8c5fdb22-2e85-11e8-8525-257a90682413.png)

To cast a more subtle shadow than an ordinary drop shadow, **shadow styles are applied to an additional layer placed below the original element, which is slightly shorter than the original element.**

see sketch file: 
get most recent file at https://app.box.com/folder/46344370140
(go to "Symbols - Shadows")

• am unclear whether the "view full comparison" button belongs to layer 2 or 3. if it will never overlap the map legend, then 2.
