### ISSUE TITLE
Use loading indicator for rankings?

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#680]
Sometimes the initial data load on rankings can take a while, should we use the loading bar service somewhere?

**Comment by Lane** [comment]
Yeah, good idea.  At minimum we should use our loading bar in the header, and also probably add a placeholder in the content area.  Either a spinner or some "Loading..." text would be good.  Or if we want to go all out we could have a wireframed outline of some bars while it loads. I think Facebook does something like that.

**Comment by pjsier** [comment]
I can take this and just add the loading bar to the header along with "Loading..." in the body for now.
