### ISSUE TITLE
Generate Icon font

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#689]
Generate an icon font, and update all icon instances used on the site:

- Down arrow
- Left arrow
- Right arrow
- Up arrow
- Email
- Link
- Facebook
- Twitter
- Github
- Search
- Zoom In (plus)
- Zoom Out (minus)
- Geolocate
- Info
- Home
- Menu
- Search
- Map
- Help
- Hint
- Close

@noelelusano to provide icons this week.

**Comment by noelelusano** [comment]
invision: https://projects.invisionapp.com/d/main#/projects/prototypes/13464455

sketch: https://app.box.com/s/f5pzp404m3tillsal8eyoh4t3q6hyg6d

**Comment by Lane** [comment]
Opting for SVG symbols instead of icon font:

https://css-tricks.com/icon-fonts-vs-svg/
https://css-tricks.com/svg-sprites-use-better-icon-fonts/
