### ISSUE TITLE
Location scrolls out of view when triggering data panel (rankings)

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#699]
From James on Slack:

> clicking any place for the first time causes that place in the rankings list to bump up out of view as the data panel appears (presumably moving up the same distance as the data panel's height?). Only happens on initial triggering of data panel.

**Comment by pjsier** [comment]
I'm not sure I fully understand this issue. Is this for clicking the location name in the data panel to trigger a scroll, or just clicking one of the bars to select a location? Clicking one of the bars doesn't trigger a scroll, so is this proposing that we should scroll after clicking a bar to make sure that it stays in view?

**Comment by Lane** [comment]
When you click the first location (or dismiss a location) the data panel is rendered causing the list to jump, and the list items you were looking at are no longer in view.  The behavior we want is for the list to stay in the same place when opening and closong the data panel.

**Comment by pjsier** [comment]
Hmm, ok that makes sense, but I'm not seeing that happen for some reason

**Comment by Lane** [comment]
here's an example, I click on number 10, then after that the list is now at position 25.

![image](http://g.recordit.co/6Lyhg0T0ar.gif)

**Comment by pjsier** [comment]
Ahh this is only an issue on Chrome (or at least it's not on Firefox). I'd been trying on Firefox without being able to replicate it, but when I tried that example on Chrome I saw the issue. Thanks for the clarification!

**Comment by Lane** [comment]
Ah yep, sorry I was assuming it was happening everywhere.  Not happening on Safari either.
