### ISSUE TITLE
Production build breaks the map component

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#7]
Something goes wrong with mapboxgl when running `ng build` with the `--prod` flag, and the map does not render.

**Comment by pjsier** [comment]
It looks like if we follow the steps in [this issue comment about Mapbox GL not working in `angular-cli`](https://github.com/angular/angular-cli/issues/5804#issuecomment-321784625) then it should work. The problem right now is that even if we fix our imports and configuration, the `angular-mapbox` package is using the unsupported import. Looking at that package, it seems like we can just remove it without too much trouble
