### ISSUE TITLE
Text overflow ellipsis styles broken

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#709]
It looks like the `text-overflow: ellipsis` styles for both UI select dropdown items and search results are broken. Guessing this was part of the larger style update

<img width="276" alt="screen shot 2018-02-26 at 9 29 26 am" src="https://user-images.githubusercontent.com/8291663/36675672-afc35394-1ad7-11e8-8ffa-3288b7e368a3.png">
<img width="391" alt="screen shot 2018-02-26 at 9 30 41 am" src="https://user-images.githubusercontent.com/8291663/36675697-bbc91eee-1ad7-11e8-8077-a9df4577c67c.png">

**Comment by Lane** [comment]
Whoops, I set a height instead of min-heght.  Will fix this right now.
