### ISSUE TITLE
App shell on initial load

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#712]
Since we're loading a good amount of resources, should we set up an app shell to indicate to users that the page is loading? https://blog.angular-university.io/angular-app-shell/

I imagine we could just use the header and something like the existing loading spinner without changing much of the design, but that's an open question

**Comment by Lane** [comment]
Yep, I'd say this is worth doing.

**Comment by pjsier** [comment]
I played around with the implementation in that link, and it looks like it'll be a lot easier to just add some elements inside `app-root` in index.html and avoid the extra configuration when we won't actually be adding much
