### ISSUE TITLE
Progress bar doesn't dismiss on page load

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#72]
With the latest version of the development branch, when the page loads the progress bar shows but doesn't go away.

Reproduction steps:
  1. Open Chrome (Version 61.0.3163.100)
  2. Go to the [map tool on the staging site](http://eviction-maps.s3-website.us-east-2.amazonaws.com/).
  3. Do not interact with the page.  It loads everything, but the progress bar does not disappear.

**Comment by pjsier** [comment]
Closed on #76
