### ISSUE TITLE
Handle NaN in rankings results

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#721]
<img width="1320" alt="screen shot 2018-02-27 at 1 09 51 pm" src="https://user-images.githubusercontent.com/8291663/36746136-8b9a71da-1bbf-11e8-88fb-7aaf121ff101.png">

**Comment by pjsier** [comment]
Question posted in Slack:
> based off of our description text, evictions can't be null, but hypothetically there could be an area that has a null evictions value, but has eviction filings. Should we exclude all areas with null evictions from the rankings?

**Comment by Lane** [comment]
Good question, I don't have an answer but maybe @james-minton does.  Or maybe something for the research team?

**Comment by james-minton** [comment]
"Null" means no data, as opposed to zero evictions? How about, rather than excluding a place that someone might hypothetically search for, we just say "Sorry, we have no eviction data for this place"?

**Comment by pjsier** [comment]
@james-minton, that makes sense, but it raises some questions like what would the auto-generated tweet text say, and what would the updated layout for that text look like? Would we still display a ranking? I'm alright going this route, but I'd prefer to just exclude them

**Comment by james-minton** [comment]
What if, instead of even triggering the data panel, a popover appears with the error text when you enter such a place? That way nothing actually happens in the tool that we'd have to account for design- or social-media wise.

I'm just foreseeing a bunch of emails from people asking why their town isn't ranked ...

**Comment by james-minton** [comment]
Maybe the specific error message for no data ... for the other places, don't we just _not_ show them as options when predictive-searching? That seems to be enough to me to suggest it's an unlisted place. Whereas maybe for a place without data, especially from a researcher or journalist's perspective, it's helpful to confirm that "we have no data here."

**Comment by james-minton** [comment]
I don't know, btw, if the toast message is the specific way to go ... just seems to nip a lot of issues in the bud

**Comment by pjsier** [comment]
The toast message works for me, and definitely creates the fewest complications. The unlisted vs. no data distinction works as well since we're pulling from the census' list, not one we created
