### ISSUE TITLE
Rankings search for location with no data sometimes returns next location

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#722]
![screen shot 2018-02-27 at 1 43 50 pm](https://user-images.githubusercontent.com/8291663/36748912-421c30e0-1bc7-11e8-820e-218e4ee86f9e.png)

Not able to replicate, but observed a few times so including here

**Comment by pjsier** [comment]
@james-minton can you still replicate this? I'm not running into this searching for Oxford, AL, which I think was the original source of this issue. We still have the bug in #780, but wanted to check if we can close this

**Comment by james-minton** [comment]
Not seeing it this time around, so hoping it's gone!

**Comment by pjsier** [comment]
Great, I'll close this for now since we've made a lot of changes since we last saw this, but we can reopen it if it shows up again
