### ISSUE TITLE
Tablet style improvements

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#725]
From #724 

> * Switching orientation doesn't always fire a window resize event. We should listen for a orientation change and then manually trigger window resize when that happens.
> * Some bottom alignment might still be off due to shrinking URL bar
> * Tapping on the map doesn't active a location, it only activates its hover state

**Comment by pjsier** [comment]
From testing this out on BrowserStack, it looks like changing orientation is consistently firing a resize event. Are there any devices I should look at in particular?

It looks like the problem is the delayed transition to handle the mobile `vh` units. One potential fix would be to remove and re-add the transition property on resize? A bit hacky, but so were a lot of the other `vh` fixes

**Comment by Lane** [comment]
Ahhh I was assuming it was the orientation change not firing resize because I've seen that in the past, but it makes more sense that it would be the delayed transition for the height. Removing / re-adding is worth a shot.  I wonder if resize triggers when the location bar shrinks?

**Comment by pjsier** [comment]
Just checked it out, and the location bar shrinking doesn't fire a resize event. About to submit a PR fixing the transition

**Comment by pjsier** [comment]
Not sure what's meant by the bottom alignment point, but are you thinking we should fire map click events on mobile/tablet hover? My hesitance there is that it's been working on mobile (at least for me), and I'm not sure what the difference with tablet there is

**Comment by Lane** [comment]
I think it should be good, I'm pretty sure #724 fixed it, just need to do more testing on different devices.

**Comment by pjsier** [comment]
I'm gonna close this and open a separate issue for the double tapping to make things more clear
