### ISSUE TITLE
States dropdown disappears into footer (rankings)

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-maps#730]
![states list disappears into footer](https://user-images.githubusercontent.com/33635008/36796807-767b8cac-1c74-11e8-9023-4cde09c636fb.gif)

Similar to #729 , this only occurs with shorter lists.

**Comment by pjsier** [comment]
I have this fixed locally by dropping the `app-footer` `z-index` to 19, but I have a feeling that might create complications in other parts of the site
