### ISSUE TITLE
Cards are sometimes added in the wrong order

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#733]
The last clicked location should always be the first card in the stack on the map.  Sometimes the last clicked card ends up in the middle or the bottom.  

Reproduction (Chrome):
- Click Texas, New Mexico, then Arizona on the map

Expected:
- Arizona should be on the top of the stack, followed by New Mexico, then Texas

What happens:
- Texas remains on top of the stack, New Mexico is inserted beneath it, then Arizona.

**Comment by pjsier** [comment]
At first I thought this was alphabetical order or order based off of FIPS code, but when I select Alaska, Montana, and Alabama (in any order), they always show up (when expanded) in the order Alabama, Montana, Alaska

**Comment by pjsier** [comment]
I dug into this a bit, and somewhere in between `tileRequests` being run through `forkJoin` and receiving data in the subscriber `activeFeatures` is being reordered. I tried changed `activeFeatures` to use a getter and setter, and then called `debugger` inside the setter, but I can't find where it's actually reordering the features. One call it will have them in the correct order, and in the next they'll have already been updated without calling the setter

**Comment by pjsier** [comment]
Closed by #740
