### ISSUE TITLE
Setup routes for top evictors

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#735]
Need to setup a route for top evictors, including the parameters that can be set by the user.  Also need to setup a router link in the nav bar so the user can switch between top evicting areas and evictors.

**Comment by pjsier** [comment]
By "router link in the nav bar", do you mean something other than this?

<img width="344" alt="screen shot 2018-03-01 at 8 28 28 am" src="https://user-images.githubusercontent.com/8291663/36849780-8cc988ae-1d2a-11e8-89d5-446d8f25cc82.png">

Or just making that actually work?

**Comment by Lane** [comment]
Just making it work
