### ISSUE TITLE
Update tab navigation, accessibility

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#743]
Not sure if this happened during one of the refactoring PRs, but it doesn't look like tab navigation is still working on the map tool

**Comment by Lane** [comment]
Which tab navigation?

**Comment by pjsier** [comment]
Sorry, I meant using `tabindex` properties to move around the page. It may just be that the `outline` property is disabled for some elements, but I haven't been able to move around the page using just tabs on Firefox or Chrome (although Chrome seems a bit better)

**Comment by Lane** [comment]
Ahhh gotcha.  Yeah, we'll need to do another pass on that.  Some of the design updates changed ordering / styles.
