### ISSUE TITLE
Add email signup before accessing data interface

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#754]
"Select data set(s)" in the map tool currently links to the S3 data interface.  It has been requested that user's must signup to access the data interface.  The following should be done to implement this:

  - [x] Obtain approval from the team that a mailchimp solution works for them
  - [x] Setup a mailchimp mailing list for "data updates"
  - [x] Create a welcome email that contains a link to the data interface for new subscribers
  - [x] Add a dialog to the map tool that has an explanation for why they must enter their email, followed by the mailing list signup form
  - [x] Add analytics tracking to see how many people signup after opening the dialog
  - [x] Update footer signup so that subscribers are added to the "newsletter" group

**Comment by Lane** [comment]
@james-minton are you able to setup the mailing list and provide the form code for signups?

**Comment by Lane** [comment]
@james-minton everything has been setup group-wise in mailchimp.  All that's needed on your end is to create an automated email anytime a new subscriber joins the "Eviction Data" group.

The link is currently data.evictionlab.org.  Is this fine, or do we want an uglier URL so it's not easily remembered / shared?

**Comment by james-minton** [comment]
Thanks and hmm ... what do you think? I'd be inclined to go with uglier, to maintain some kind of theater around security, at least

**Comment by Lane** [comment]
Yeah, I think a less readable URL makes sense if they want to hide it.  The url to add in the email will be https://d4fgopbpce9dc.cloudfront.net/ in that case.

**Comment by Lane** [comment]
I have added an automation email to mailchimp for the "Eviction Data" group.  The email can be editing in the "added to group" campaign.
