### ISSUE TITLE
Activating feature on iPad requires two taps

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#756]
Tapping on a map feature on tablet doesn't activate a feature, it just triggers the hover state. It requires two taps to activate. Haven't observed this on mobile, and not sure if it's only on iPad. Split out from #725

**Comment by pjsier** [comment]
I tried this on a Kindle Fire using Amazon's Silk Browser (pretty random) and it only took one tap. Do we have confirmation that this is just for iPads?

**Comment by Lane** [comment]
Yeah, it happens for me on iPad using iOS simulator, and I think @james-minton had mentioned it's happening on his physical device.

**Comment by james-minton** [comment]
Yep, still 2 taps on my iPad.

**Comment by pjsier** [comment]
I tried this on a Google Nexus in BrowserStack, and it only takes one tap so I'm updating the issue title to clarify that this only seems to happen on iPad (it's not a problem on my iPhone or emulated iPhones)

**Comment by james-minton** [comment]
Can corroborate that it doesn't happen on my iPhone
