### ISSUE TITLE
Ranking panel no longer displaying

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#759]
It looks like one of the recent commits is causing the rankings panel not to display in the current viewport with `position: sticky`. Now it's getting stuck at the bottom

**Comment by Lane** [comment]
This is the weirdest thing... but somehow 

```
html { overflow-x: hidden; }
```

causes `position: sticky` not to work anymore.

**Comment by pjsier** [comment]
Closed by #760
