### ISSUE TITLE
SVG linear gradients don't work in deployed sites with base href set on iOS

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#764]
Seen in iOS Chrome and Firefox, and it might have something to do with the gradient. I guess we ran out of orange?

![img_1524](https://user-images.githubusercontent.com/8291663/37101090-51d43f5e-21ea-11e8-9898-441f2faed283.PNG)

**Comment by pjsier** [comment]
So this actually looks like it's an issue with the `<base>` tag. The `url()` call in the template isn't handled the same way as Angular handles it in the CSS, so it breaks the association. I've seen some ways around it, like specifying the absolute URL, but it sounds like that might try and load the page each time. Would it make sense to just move these into assets rather than having them inline?

**Comment by pjsier** [comment]
It looks like this isn't about the `<base>` tag alone, because I deployed a prototype with the `href` set, and the gradients are loading on iOS. I'm wondering if it could have something to do with the S3 error returning the same page as index, but still giving a 404. That might be something we can change with Lambda@Edge

**Comment by Lane** [comment]
seems like a hefty fix for some gradients.  We could fall back to a solid color with CSS on iOS devices?
