### ISSUE TITLE
General accessibility updates, review

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#792]
Creating this as a catchall for any accessibility issues that we need to fix

**Comment by Lane** [comment]
Did a review this morning and a few things that still need to be fixed up

- Dialog windows: should restore focus to the button that opened them when they are closed
- Opening the menu should give focus to the first menu item / closing the menu should give focus to the menu button
- "View More" button should bring focus to data panel area
- "Back to Map" should bring focus to map area
- Feature overview dialog needs `aria-label` on buttons
- Send data dialog needs checkbox label for opt-in
- Add labels for input fields using placeholder only

**Comment by pjsier** [comment]
Closing this general issue, creating a new one specifically for updating the gray text for contrast
