### ISSUE TITLE
Windows: Page width changes when zooming the map

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#828]
- **Device/Browser**: Windows 10/IE11/Edge/Chrome/Firefox
  - **Resolution:** 1280x720
  - **Problem**: When zooming the map the scroll bar disappears, causing a change in the page width and certain page elements to shift position.
  - **Expected**: Page elements should remain in place when zooming the map
  - **To Reproduce:** Load page on a windows device, zoom in or out on the map.

**Comment by pjsier** [comment]
This is caused by setting `position: fixed` and `overflow-y: scroll` in the scroll service, right? https://github.com/EvictionLab/eviction-maps/blob/development/src/app/services/scroll.service.ts#L29
