### ISSUE TITLE
IE11: Map outline performance

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#830]
- **Device/Browser**: Windows 10/IE 11
  - **Resolution:** 1280x720
  - **Problem**: When using the map it takes a very long time for the outlines on different geographies to show when hovering.  The tooltip updates quickly though.
  - **Expected**:  When hovering a location the outline should appear in under a second.
  - **To Reproduce:**  Worst case happens when there are several shapes rendered on the map at once (e.g. counties at a low zoom).  Go to counties at a low zoom level and begin moving the mouse around the map.  The tooltip will show but the outline won't for a few seconds.  Seems like the more you move the mouse around, the longer it takes to show the outline. Potential performance bottle neck.

Either need to enhance performance on adding the shape outline, or drop hover outlining in IE11.

**Comment by pjsier** [comment]
It's also a little slow on Firefox (though not nearly as bad), and from timing some pieces it's nothing in our code. All of the functions for creating a union feature and setting the updated source data run quickly, it's just the WebGL context updating that's slow. If it's that slow on IE I think it could make sense to just drop it there, but it's fast enough to be worth keeping on Firefox
