### ISSUE TITLE
IE11/Edge: Feature Overview Problems

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#836]
- **Device/Browser**: Windows 10/IE11/Edge
  - **Resolution:** 1280x720
  - **Problem**: A couple:
    - IE11/Edge: Animations do not display properly (missing vendor prefixes?)
    - IE11: Text doesn't wrap and instead overflows into next slide

**Comment by pjsier** [comment]
There are similar issues on Safari 9 on El Capitan. The animation for the first slide plays, but after clicking next once, none of the other animations start (including the first slide after clicking back to it). Everything displays fine, just as static images

**Comment by Lane** [comment]
I think the Safari thing is caused by something else, I'll add a separate issue for that.
