### ISSUE TITLE
Switch geography before finished loading

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#838]
Most noticable on IE11 because of long loading times, but if possible we should switch the geography earlier when searching an area with a different geography than the current one.

**Example:**
  - search a location that is a different geography than you are currently on (e.g. Searching a city while viewing a block group)
  - select that location in the search
  - the map pans / zooms to that location, waits for all of the data to load (for block groups), *then* switches geography to cities and loads the data for that.

**Proposed changes:**
  - Switch the geography to the new geography immediately after selecting an item with different geography from search.

**Comment by pjsier** [comment]
I like this idea, but I think the reason we set it this way in the first place is that it doesn't work if the starting zoom is less than the new layer's minimum zoom. Could we potentially only switch the geography at the start of the switch if the layer is within the zoom range?

**Comment by Lane** [comment]
Hmm.. Would be nice if we could make a fix that works for all cases.  Maybe not switching the geography immediately, but switching once the map view reaches it's new destination?

**Comment by pjsier** [comment]
I think we changed the `zoom` handler to `zoomstart` and `zoomend` for performance reasons, but maybe we could set an observable on `zoomstart` that only fires once the minimum zoom threshold has been crossed?

**Comment by Lane** [comment]
`zoomend` is fine, that would trigger once the map has finished moving to it's new spot right?

**Comment by pjsier** [comment]
Yep, that would work. I actually thought we were using that already, but it turns out we're waiting for the map to finish loading which is definitely taking a lot more time.  All we'll need to do is change this part https://github.com/EvictionLab/eviction-maps/blob/development/src/app/map-tool/map-tool.component.ts#L232 to listen for `zoomend` by maybe adding that to the service in addition to loading?
