### ISSUE TITLE
Firefox <=54: SVGs with use tag don't display

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#849]
- **Device/Browser**: Firefox <=54
  - **Problem**: Because we're setting `href` in the `base` tag, it breaks SVG linking on older versions of Firefox
<img width="1308" alt="screen shot 2018-03-20 at 11 51 59 am" src="https://user-images.githubusercontent.com/8291663/37670120-82839fc2-2c36-11e8-822a-4da27bf7a4b0.png">

We may be able to fix it setting `xml:base` on the SVG elements, or by injecting the current base URL into the `app-ui-icon` `xlink:href`

**Comment by pjsier** [comment]
So neither of these fixes seemed to work for me. I set `xml:base` and then tried prepending the base href in `xlink:href`, but I'm still seeing the issue. Prototype I've been working with is here http://eviction-lab-prototypes.s3-website.us-east-2.amazonaws.com/firefox-svg/

Prepending the base href in `xlink:href` breaks the SVGs on more recent version of Firefox (and maybe other browsers, I haven't checked yet), so that's probably not on the table even if we get it working

**Comment by pjsier** [comment]
This isn't a great fix, but since neither of those options worked, what do you think of copying the current inline SVG definition into a separate `icons.svg` file, and loading from that rather than the current page for specific browsers @lane?

**Comment by Lane** [comment]
I think we'd lose IE support if we did that... Starting to wonder if we should ditch `<base href="/">` and just use hash routing.

**Comment by pjsier** [comment]
I've started thinking the same thing. Honestly we only have year as a required parameter on the map and tab on rankings. It might even be worth converting both of those to query parameters with defaults? This is more of a subjective thing, but I think query parameters look cleaner

**Comment by Lane** [comment]
I think we need the first route parameter so that the app bootstraps to the proper component (map or ranking). I'd support dropping to hash routing though, as non-hash routing seems to cause more problems than it solves.

**Comment by pjsier** [comment]
That works for me! I think the only thing that ran into complications one way or another was the embed component, but we left the fix in there for handling hash routing so we shouldn't have to change anything
