### ISSUE TITLE
check sizing on arrows in dropdowns

### ISSUE THREAD

**Issue by noelelusano** [EvictionLab/eviction-maps#858]
![image](https://user-images.githubusercontent.com/6036323/37738675-f0865d82-2d14-11e8-9494-1d924867d2c5.png)

sketch: 
grab most recent file here -
https://app.box.com/folder/46344370140
go to "Symbols - Dropdowns"

**Comment by Lane** [comment]
@noelelusano are the arrows supposed to be 16x16 on all resolutions for the rankings panel?

It looks a bit off on large resolutions to me:

![image](https://user-images.githubusercontent.com/21034/37746148-5d384dae-2d3e-11e8-9508-71e8dd56b949.png)
