### ISSUE TITLE
style fixes for graph control bar section

### ISSUE THREAD

**Issue by noelelusano** [EvictionLab/eviction-maps#859]
![image](https://user-images.githubusercontent.com/6036323/37738918-cafb6926-2d15-11e8-9359-cbb195878789.png)

• toggles and dropdowns sized to 40px high, with exception of judgments/filings toggle for 320 breakpoint--32px
• font for toggles has changed from Akkurat to a combination of GT Eesti Bold/Medium depending on selected state, with exception of 320 breakpoint where font remains the same
• line graph/bar graph toggle has a label, and that element has been moved inline with other controls where possible
• no changes to the graph legend

sketch: 
grab most recent file here -
https://app.box.com/folder/46344370140
go to "Symbols - Graph"

**Comment by Lane** [comment]
@noelelusano should all of the dropdowns be 40px high, or just these ones on the graph?
