### ISSUE TITLE
Data panel does not display on click

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#86]
Looks like I missed this on reviewing #85, but on click when features are loaded, the data panel does not display. I'm guessing a style property wasn't moved over

**Comment by Lane** [comment]
I turned off the panel overlap, it still shows up, but you have to scroll to get to it.  I don't have the cards setup yet, so you have to scroll on a non-map element to get to it for now.  This will be fixed once the card implementation is in.

**Comment by pjsier** [comment]
Ah gotcha, thanks for the clarification!
