### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#866]
Just tried searching "Natchitoches Parish, Louisiana" and received a loading bar that sits forever.

Received this error in the console:
![image](https://user-images.githubusercontent.com/21034/37785270-5ba82d48-2dbf-11e8-805a-7f05b855b21e.png)

We should probably add some error handling to the search to notify the user if something goes wrong.

**Comment by pjsier** [comment]
Is this on beta or staging? Beta doesn't have some fixes that are in staging, and it's working on staging for me

**Comment by pjsier** [comment]
Closing this and opening a new issue for a general search error handler
