### ISSUE TITLE
Add event for download error

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#877]
It might be worthwhile to add analytics events on errors, mainly for something like the download form where it can also submit the parameters that were supplied. It could also be useful for search so that we can find any locations with issues

**Comment by Lane** [comment]
Agreed!  I was reading this and it seems like a good approach for our setup: https://www.kevinleary.net/javascript-error-tracking-google-tag-manager/

Does that work for you or were you thinking something else?

**Comment by Lane** [comment]
That sounds good.  I will do the GTM setup if that works?

**Comment by pjsier** [comment]
Works for me! I haven't worked much with it anyway

**Comment by Lane** [comment]
I've added the GTM setup, so any javascript errors thrown on the front end will get logged to Google Analytics.  It will log:

  - Error Message
  - Error Line
  - Script URL
  - Page URL

The error line and script URL probably aren't that helpful, so as long as we throw meaningful error messages we should be good.
