### ISSUE TITLE
Flag Maryland and 99th percentile data

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-maps#921]
Need to implement a way to flag high eviction rates (in the 99th percentile), and also flag when a user is looking at Maryland.

I'm thinking we could have a dismissible (but not auto dismissible) toast message that shows when they activate a location in the 99th percentile, OR when the map bounds are within a Maryland bounding box.

**Comment by pjsier** [comment]
My worry about this is that we're only really using toasts for errors, and this is a different kind of information. At the risk of more overload, could we do some kind of styled underline treatment on location cards that shows a tooltip (or even modal) on hover/click?

**Comment by Lane** [comment]
True, we could add an additional style to toast messages? One for info and one for errors.

Concern with the underline / tooltip is they might not see it, especially if they are just looking at Maryland and don't activate any of the areas.

Not really sold on either method though, @noelelusano do you have any thoughts?

**Comment by pjsier** [comment]
I didn't get the sense that we would need to show it if they're just looking at Maryland and haven't activated anything, and that would mean we'd have to show whatever indicator on the map on initial page load which feels like a bit much

**Comment by Lane** [comment]
Yeah, that's fair.  I was thinking we'd only show it when the map is zoomed in enough and Maryland is taking up the majority of the viewport.  Thinking about it a bit more, probably not the best approach because it adds complexity and if someone is that zoomed in on Maryland they're probably going to click on something.

I'm for the underline / tooltip approach if we can pull it off.

**Comment by pjsier** [comment]
Is this closed now that #965 is merged?

**Comment by Lane** [comment]
Yep!
