### ISSUE TITLE
Ranking panel robo-text only shows eviction numbers

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#945]
We should probably display whatever is currently selected

**Comment by Lane** [comment]
The selected data (e.g. eviction filing rate) is shown under the location name, but yeah, the robo text is always evictions and never filings.  @james-minton what do you think, should it be reflective of filings when they have eviction filings or filing rate selected?

**Comment by james-minton** [comment]
Thanks -- per Matt, answer is yes. Language is here (note that this has been pretty finely parsed by Research and should be copied over verbatim):

Filings:
There were [FILINGS NUMBER] eviction filings in the Richmond area in [YEAR]. That amounts to [NUMBER] households threatened with eviction every day. There were [NUMBER] eviction filings for every 100 renter homes in [YEAR].
 
Evictions:
There were [JUDGMENT NUMBER] evictions in the Richmond area in [YEAR]. That amounts to [NUMBER] households evicted every day. 11.44 in 100 renter homes are evicted in [YEAR].

**Comment by pjsier** [comment]
Replaced by #950
