### ISSUE TITLE
restyle footer for all breakpoints

### ISSUE THREAD

**Issue by noelelusano** [EvictionLab/eviction-maps#953]
@james-minton @Lane 
we had to add new items to the footer which has altered the layout and hierarchy.

please see most recent file @ https://app.box.com/folder/46344370140
go to: Symbols - Footer

• for 320 have gotten rid of alternate square logo image (instead of horizontal logo image used everywhere else) to conserve space
• please use "middot;" for bullet point separator beneath "FUNDERS"

**Comment by noelelusano** [comment]
@james-minton @Lane minor update to most recent file @ https://app.box.com/s/ltdtme0ywwdu3sm4fjbvrtt26bwy6f4o - if you downloaded it please redownload.

• added attribution for hero image

**Comment by Lane** [comment]
@noelelusano will people know what "Hero photo" means?

**Comment by james-minton** [comment]
Alternative suggestions welcome!

**Comment by Lane** [comment]
Inline attribution?

![image](https://user-images.githubusercontent.com/21034/38178215-1a28f834-35cb-11e8-8fe7-70ba520f257f.png)

**Comment by pjsier** [comment]
Is this closed by #972?

**Comment by Lane** [comment]
Yep.
