### ISSUE TITLE
Add suggested citation to data download page

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-maps#954]
Per Matt:

> I’d like to include this suggested acknowledgement:
> 
> This research uses data from The Eviction Lab at Princeton University, a project directed by Matthew Desmond and designed by Ashley Gromis, Lavar Edmonds, James Hendrickson, Katie Krywokulski, Lillian Leung, and Adam Porton. The Eviction Lab is funded by the JBP, Gates, and Ford Foundations as well as the Chan Zuckerberg Initiative. More information is found at www.evictionlab.org.     
> 
> I’d like to ask everyone who downloads the data to send us papers/products that use the data.

For the last part, here's my wording:

If you use this data in your research or reporting, please **share it with us**! (Bold = link to /contact page)

**Comment by james-minton** [comment]
(This would go at the top of the data page.)

**Comment by pjsier** [comment]
<img width="988" alt="screen shot 2018-03-31 at 9 02 26 am" src="https://user-images.githubusercontent.com/8291663/38163961-48de2c94-34c2-11e8-899c-fffbd5679d34.png">

Updated
