### ISSUE TITLE
Long property names cause alignment issues

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#961]
Not sure when this first showed up, but noticed it on the data panel in desktop

<img width="847" alt="screen shot 2018-03-31 at 9 03 48 am" src="https://user-images.githubusercontent.com/8291663/38163971-841c13ca-34c2-11e8-9e53-747420e8c28d.png">

**Comment by Lane** [comment]
Ah, this is because of one of the tooltip changes from yesterday.  Will fix up today.
