### ISSUE TITLE
Display message when no areas match rankings filters

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#970]
Should we display some kind of message when no areas are returned for a given set of filters on the rankings page? Here's one example:

<img width="1188" alt="screen shot 2018-04-02 at 10 30 01 am" src="https://user-images.githubusercontent.com/8291663/38202542-afc9e0f6-3661-11e8-88c5-9898a3b93bda.png">

**Comment by Lane** [comment]
Yep, I'll set this up.

**Comment by pjsier** [comment]
Closed by #974
