### ISSUE TITLE
Horizontal overflow on mobile map and rankings

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-maps#986]
Not sure if these are related, and I think the map may be related to #985, but I'm able to scroll past the main body content on mobile for both map and rankings. I can't always reproduce it, but I've got some screenshots:

<img width="542" alt="screen shot 2018-04-02 at 5 45 57 pm" src="https://user-images.githubusercontent.com/8291663/38220050-02670672-369e-11e8-8d5b-6f0ddcbc270f.png">

<img width="535" alt="screen shot 2018-04-02 at 5 47 05 pm" src="https://user-images.githubusercontent.com/8291663/38220065-0e978a34-369e-11e8-8139-97f004d0759b.png">

**Comment by Lane** [comment]
Hmm.. having a hard time replicating.  Is this iOS?  Which device / resolution / browser?

**Comment by pjsier** [comment]
iOS Chrome, and I'd have to look up the specific resolution

**Comment by Lane** [comment]
Which hardware, don't need the resolution if I can get that.

**Comment by pjsier** [comment]
iPhone 7
