### ISSUE TITLE
set a consistent width for expanded legend

### ISSUE THREAD

**Issue by noelelusano** [EvictionLab/eviction-maps#989]
![image](https://user-images.githubusercontent.com/6036323/38220569-bb316242-368f-11e8-86b1-f3c2a5b66518.png)
![image](https://user-images.githubusercontent.com/6036323/38220572-c20f388c-368f-11e8-8654-20c277004835.png)

• zooming through map, the width of the expanded legend shifts. please make consistent so it looks smooth across zoom.

**Comment by pjsier** [comment]
I think this is because of the labels for the bubbles changing, but that still shouldn't change the width so we can fix that
